color:
  when: auto
  theme: custom

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

date: relative

icons:
  theme: fancy
  separator: " "
  # TODO: File type icons have priority over directory and executable
  # icons. It'd be nice if you could override that.
  #
  # This issue is for letting the directory icon have precedence over file type:
  # https://github.com/lsd-rs/lsd/issues/965
  when: always

total-size: false

hyperlink: auto

symlink-arrow: " "

display: almost-all

header: true
