# The goal is to have icons for different file types so I can distinguish between them, like `--classify`.

filetype:
  file: ""
  dir: ""
  pipe: ""
  socket: ""
  executable: ""
  symlink-dir: ""
  symlink-file: ""
  device-char: ""
  device-block: ""
  special: ""

# Remove default icons for files with certain names or extensions, for reasons
# stated at the top of the file. Some of these names are directories though so
# they will be given an icon.
#
# TODO: This won"t cover icons that get added in the future for file
# extensions/names not listed here. Ideally I could use a regex to capture all
# file names/extensions.
name:
  .atom: ""
  .bash_history: ""
  .bash_logout: ""
  .bash_profile: ""
  .bashrc: ""
  .cache: ""
  .cargo: ""
  .clang-format: ""
  .config: ""
  .doom.d: ""
  .ds_store: ""
  .editorconfig: ""
  .emacs.d: ""
  .env: ""
  .eslintrc.json: ""
  .git-credentials: ""
  .git: ""
  .gitattributes: ""
  .gitconfig: ""
  .github: ""
  .gitignore: ""
  .gitlab-ci.yml: ""
  .gitmodules: ""
  .gnupg: ""
  .htaccess: ""
  .htpasswd: ""
  .inputrc: ""
  .jupyter: ""
  .mozilla: ""
  .mypy_cache: ""
  .nix-defexpr: ""
  .node_repl_history: ""
  .npm: ""
  .pki: ""
  .profile: ""
  .python_history: ""
  .release.toml: ""
  .rustup: ""
  .rvm: ""
  .shellcheckrc: ""
  .sqlite_history: ""
  .ssh: ""
  .trash: ""
  .vim: ""
  .viminfo: ""
  .vimrc: ""
  .vscode: ""
  .xauthority: ""
  .xinitrc: ""
  .xresources: ""
  .yarnrc: ""
  .zsh_history: ""
  .zshrc: ""
  a.out: ""
  assets: ""
  authorized_keys: ""
  bin: ""
  bspwmrc: ""
  cargo.lock: ""
  cargo.toml: ""
  changelog: ""
  composer.json: ""
  config.ac: ""
  config.el: ""
  config.mk: ""
  config: ""
  contributing: ""
  cron.d: ""
  cron.daily: ""
  cron.hourly: ""
  cron.monthly: ""
  cron.weekly: ""
  crontab: ""
  crypttab: ""
  custom.el: ""
  desktop: ""
  dist: ""
  doc: ""
  docker-compose.yml: ""
  dockerfile: ""
  documents: ""
  downloads: ""
  etc: ""
  favicon.ico: ""
  fstab: ""
  gitignore_global: ""
  go.mod: ""
  go.sum: ""
  gradle: ""
  group: ""
  gruntfile.coffee: ""
  gruntfile.js: ""
  gruntfile.ls: ""
  gshadow: ""
  gulpfile.coffee: ""
  gulpfile.js: ""
  gulpfile.ls: ""
  hidden: ""
  home: ""
  hostname: ""
  hosts: ""
  htoprc: ""
  include: ""
  init.el: ""
  known_hosts: ""
  lib: ""
  libexec: ""
  license.md: ""
  license.txt: ""
  license: ""
  localized: ""
  mail: ""
  maintainers: ""
  makefile.ac: ""
  makefile: ""
  music: ""
  muttrc: ""
  node_modules: ""
  npmignore: ""
  nvim: ""
  package-lock.json: ""
  package.json: ""
  packages.el: ""
  passwd: ""
  pictures: ""
  profile: ""
  public: ""
  rc.lua: ""
  readme: ""
  robots.txt: ""
  root: ""
  rubydoc: ""
  sbin: ""
  scripts: ""
  shadow: ""
  share: ""
  shells: ""
  src: ""
  static: ""
  sudoers: ""
  sxhkdrc: ""
  template: ""
  tests: ""
  tigrc: ""
  url: ""
  vagrantfile: ""
  vendor: ""
  videos: ""
  webpack.config.js: ""
  xbps.d: ""
  xmonad.hs: ""
  xorg.conf.d: ""
extension:
  1: ""
  2: ""
  3: ""
  4: ""
  5: ""
  6: ""
  7: ""
  8: ""
  7z: ""
  a: ""
  ai: ""
  ape: ""
  apk: ""
  asc: ""
  asm: ""
  asp: ""
  avi: ""
  avro: ""
  awk: ""
  bash: ""
  bash_history: ""
  bash_profile: ""
  bashrc: ""
  bat: ""
  bin: ""
  bio: ""
  bmp: ""
  bz2: ""
  c++: ""
  c: ""
  cc: ""
  cfg: ""
  cl: ""
  class: ""
  clj: ""
  cljs: ""
  cls: ""
  coffee: ""
  cjs: ""
  conf: ""
  cp: ""
  cpp: ""
  cs: ""
  csh: ""
  cshtml: ""
  csproj: ""
  css: ""
  csv: ""
  csx: ""
  cue: ""
  cxx: ""
  dart: ""
  db: ""
  deb: ""
  desktop: ""
  diff: ""
  dll: ""
  doc: ""
  dockerfile: ""
  documents: ""
  docx: ""
  ds_store: ""
  dump: ""
  ebook: ""
  editorconfig: ""
  ejs: ""
  el: ""
  elc: ""
  elf: ""
  elm: ""
  env: ""
  eot: ""
  epub: ""
  erb: ""
  erl: ""
  ex: ""
  exe: ""
  exs: ""
  fish: ""
  flac: ""
  flv: ""
  font: ""
  fpl: ""
  fs: ""
  fsi: ""
  fsx: ""
  gdoc: ""
  gemfile: ""
  gemspec: ""
  gform: ""
  gif: ""
  git: ""
  go: ""
  gradle: ""
  gsheet: ""
  gslides: ""
  guardfile: ""
  gz: ""
  h: ""
  hbs: ""
  heic: ""
  heif: ""
  heix: ""
  hpp: ""
  hs: ""
  htm: ""
  html: ""
  hxx: ""
  ico: ""
  image: ""
  img: ""
  iml: ""
  ini: ""
  ipynb: ""
  iso: ""
  jar: ""
  java: ""
  jl: ""
  jpeg: ""
  jpg: ""
  js: ""
  json: ""
  jsonc: ""
  jsx: ""
  key: ""
  ksh: ""
  ld: ""
  ldb: ""
  less: ""
  lhs: ""
  license: ""
  lisp: ""
  localized: ""
  lock: ""
  log: ""
  lua: ""
  lz: ""
  m3u8: ""
  m3u: ""
  m4a: ""
  m4v: ""
  magnet: ""
  man: ""
  markdown: ""
  md: ""
  mjs: ""
  mkd: ""
  mkv: ""
  mobi: ""
  mov: ""
  mp3: ""
  mp4: ""
  msi: ""
  mustache: ""
  nix: ""
  npmignore: ""
  o: ""
  ogg: ""
  ogv: ""
  opus: ""
  otf: ""
  pdf: ""
  pem: ""
  phar: ""
  php: ""
  pkg: ""
  pl: ""
  plist: ""
  pls: ""
  pm: ""
  png: ""
  ppt: ""
  pptx: ""
  procfile: ""
  properties: ""
  ps1: ""
  psd: ""
  pub: ""
  pxm: ""
  py: ""
  pyc: ""
  r: ""
  rakefile: ""
  rar: ""
  razor: ""
  rb: ""
  rdata: ""
  rdb: ""
  rdoc: ""
  rds: ""
  readme: ""
  rlib: ""
  rmd: ""
  rpm: ""
  rproj: ""
  rs: ""
  rspec: ""
  rspec_parallel: ""
  rspec_status: ""
  rss: ""
  rtf: ""
  ru: ""
  rubydoc: ""
  s: ""
  sass: ""
  scala: ""
  scpt: ""
  scss: ""
  sh: ""
  shell: ""
  sig: ""
  slim: ""
  sln: ""
  so: ""
  sql: ""
  sqlite3: ""
  srt: ""
  styl: "  " # typos:ignore
  stylus: ""
  sub: ""
  sublime-package: ""
  sublime-session: ""
  svg: ""
  swift: ""
  swp: ""
  sym: ""
  t: ""
  tar: ""
  tex: ""
  tgz: ""
  tiff: ""
  toml: ""
  torrent: ""
  ts: ""
  tsx: ""
  ttc: ""
  ttf: ""
  twig: ""
  txt: ""
  video: ""
  vim: ""
  vlc: ""
  vue: ""
  wav: ""
  webm: ""
  webp: ""
  windows: ""
  wma: ""
  wmv: ""
  woff2: ""
  woff: ""
  wpl: ""
  xbps: ""
  xcf: ""
  xls: ""
  xlsx: ""
  xml: ""
  xul: ""
  xz: ""
  yaml: ""
  yml: ""
  zip: ""
  zsh-theme: ""
  zsh: ""
  zshrc: ""
  zst: ""
