syntax_theme = "EightiesDark"

[skin]
default = "#D8DEE9 #1d2129"
tree = "#78849b #1d2129"
parent = "#D8DEE9 #1d2129"
file = "#D8DEE9 #1d2129"
directory = "#D8DEE9 #1d2129"
exe = "#D8DEE9 #1d2129"
link = "#D8DEE9 #1d2129"
pruning = "#78849b #1d2129 Italic"
perm__ = "#78849b #1d2129"
perm_r = "#78849b #1d2129"
perm_w = "#78849b #1d2129"
perm_x = "#78849b #1d2129"
owner = "#D8DEE9 #1d2129"
group = "#78849b #1d2129"
dates = "#D8DEE9 #1d2129"
selected_line = "#D8DEE9 #2f333e / #D8DEE9 #1d2129"
char_match = "#8FBCBB #1d2129"
input = "#D8DEE9 #1d2129"
status_error = "#BF616A #2f333e"
status_job = "#BF616A #2f333e"
status_normal = "#D8DEE9 #2f333e"
status_italic = "#8FBCBB #2f333e"
status_bold = "#D8DEE9 #2f333e Bold"
status_code = "#D8DEE9 #2f333e"
status_ellipsis = "#D8DEE9 #2f333e"
scrollbar_track = "#eef0f2"
scrollbar_thumb = "#d1d3d5"
help_paragraph = "#D8DEE9 #1d2129"
help_bold = "#D8DEE9 #1d2129 Bold"
help_italic = "#D8DEE9 #2f333e Italic"
help_code = "#8FBCBB #1d2129"
help_headers = "#D8DEE9 #1d2129 Underlined"
help_table_border = "#78849b #1d2129"
preview_title = "#D8DEE9 #1d2129"
preview = "#D8DEE9 #1d2129"
preview_line_number = "#1d2129 #1d2129"
preview_match = "#8FBCBB #2f333e"
good_to_bad_0 = "#A3BE8C"
good_to_bad_1 = "#A3BE8C"
good_to_bad_2 = "#A3BE8C"
good_to_bad_3 = "#EBCB8B"
good_to_bad_4 = "#EBCB8B"
good_to_bad_5 = "#d08770"
good_to_bad_6 = "#d08770"
good_to_bad_7 = "#BF616A"
good_to_bad_8 = "#BF616A"
good_to_bad_9 = "#BF616A"
mode_command_mark = "#D8DEE9 #1d2129 Bold"
# Not sure where these are used
hex_null = "#D8DEE9 #1d2129"
hex_ascii_graphic = "#D8DEE9 #1d2129"
hex_ascii_whitespace = "#D8DEE9 #1d2129"
hex_ascii_other = "#D8DEE9 #1d2129"
hex_non_ascii = "#D8DEE9 #1d2129"
staging_area_title = "#D8DEE9 #1d2129"
sparse = "#D8DEE9 #1d2129"
content_extract = "#D8DEE9 #1d2129"
content_match = "#D8DEE9 #1d2129"
purpose_normal = "#D8DEE9 #1d2129"
purpose_italic = "#D8DEE9 #1d2129"
purpose_bold = "#D8DEE9 #1d2129"
purpose_ellipsis = "#D8DEE9 #1d2129"
file_error = "#D8DEE9 #1d2129"
flag_label = "#D8DEE9 #1d2129"
flag_value = "#D8DEE9 #1d2129"
count = "#D8DEE9 #1d2129"
