syntax_theme = "EightiesDark"

[skin]
default = "#E6ECF7 #1d2129"
tree = "#A5ABBC #1d2129"
parent = "#E6ECF7 #1d2129"
file = "#E6ECF7 #1d2129"
directory = "#E6ECF7 #1d2129"
exe = "#E6ECF7 #1d2129"
link = "#E6ECF7 #1d2129"
pruning = "#A5ABBC #1d2129 Italic"
perm__ = "#A5ABBC #1d2129"
perm_r = "#A5ABBC #1d2129"
perm_w = "#A5ABBC #1d2129"
perm_x = "#A5ABBC #1d2129"
owner = "#E6ECF7 #1d2129"
group = "#A5ABBC #1d2129"
dates = "#E6ECF7 #1d2129"
selected_line = "#E6ECF7 #2f333e / #E6ECF7 #1d2129"
char_match = "#9BC8C7 #1d2129"
input = "#E6ECF7 #1d2129"
status_error = "#BF616A #2f333e"
status_job = "#BF616A #2f333e"
status_normal = "#E6ECF7 #2f333e"
status_italic = "#9BC8C7 #2f333e"
status_bold = "#E6ECF7 #2f333e Bold"
status_code = "#E6ECF7 #2f333e"
status_ellipsis = "#E6ECF7 #2f333e"
scrollbar_track = "#242833"
scrollbar_thumb = "#eef0f2"
help_paragraph = "#E6ECF7 #1d2129"
help_bold = "#E6ECF7 #1d2129 Bold"
help_italic = "#E6ECF7 #2f333e Italic"
help_code = "#9BC8C7 #1d2129"
help_headers = "#E6ECF7 #1d2129 Underlined"
help_table_border = "#A5ABBC #1d2129"
preview_title = "#E6ECF7 #1d2129"
preview = "#E6ECF7 #1d2129"
preview_line_number = "#1d2129 #1d2129"
preview_match = "#9BC8C7 #2f333e"
good_to_bad_0 = "#A3BE8C"
good_to_bad_1 = "#A3BE8C"
good_to_bad_2 = "#A3BE8C"
good_to_bad_3 = "#EBCB8B"
good_to_bad_4 = "#EBCB8B"
good_to_bad_5 = "#d08770"
good_to_bad_6 = "#d08770"
good_to_bad_7 = "#BF616A"
good_to_bad_8 = "#BF616A"
good_to_bad_9 = "#BF616A"
mode_command_mark = "#E6ECF7 #1d2129 Bold"
# Not sure where these are used
hex_null = "#E6ECF7 #1d2129"
hex_ascii_graphic = "#E6ECF7 #1d2129"
hex_ascii_whitespace = "#E6ECF7 #1d2129"
hex_ascii_other = "#E6ECF7 #1d2129"
hex_non_ascii = "#E6ECF7 #1d2129"
staging_area_title = "#E6ECF7 #1d2129"
sparse = "#E6ECF7 #1d2129"
content_extract = "#E6ECF7 #1d2129"
content_match = "#E6ECF7 #1d2129"
purpose_normal = "#E6ECF7 #1d2129"
purpose_italic = "#E6ECF7 #1d2129"
purpose_bold = "#E6ECF7 #1d2129"
purpose_ellipsis = "#E6ECF7 #1d2129"
file_error = "#E6ECF7 #1d2129"
flag_label = "#E6ECF7 #1d2129"
flag_value = "#E6ECF7 #1d2129"
count = "#E6ECF7 #1d2129"
