syntax_theme = "GitHub"

[skin]
default = "#000000 #ffffff"
tree = "#595959 #ffffff"
parent = "#000000 #ffffff"
file = "#000000 #ffffff"
directory = "#000000 #ffffff"
exe = "#000000 #ffffff"
link = "#000000 #ffffff"
pruning = "#595959 #ffffff Italic"
perm__ = "#595959 #ffffff"
perm_r = "#595959 #ffffff"
perm_w = "#595959 #ffffff"
perm_x = "#595959 #ffffff"
owner = "#000000 #ffffff"
group = "#595959 #ffffff"
dates = "#000000 #ffffff"
selected_line = "#000000 #e3e5e7 / #000000 #ffffff"
char_match = "#71101f #ffffff"
input = "#000000 #ffffff"
status_error = "#cf222e #e3e5e7"
status_job = "#cf222e #e3e5e7"
status_normal = "#000000 #e3e5e7"
status_italic = "#71101f #e3e5e7"
status_bold = "#000000 #e3e5e7 Bold"
status_code = "#000000 #e3e5e7"
status_ellipsis = "#000000 #e3e5e7"
scrollbar_track = "#eef0f2"
scrollbar_thumb = "#000000"
help_paragraph = "#000000 #ffffff"
help_bold = "#000000 #ffffff Bold"
help_italic = "#000000 #e3e5e7 Italic"
help_code = "#71101f #ffffff"
help_headers = "#000000 #ffffff Underlined"
help_table_border = "#595959 #ffffff"
preview_title = "#000000 #ffffff"
preview = "#000000 #ffffff"
preview_line_number = "#ffffff #ffffff"
preview_match = "#71101f #e3e5e7"
good_to_bad_0 = "#116329"
good_to_bad_1 = "#116329"
good_to_bad_2 = "#116329"
good_to_bad_3 = "#e9873a"
good_to_bad_4 = "#e9873a"
good_to_bad_5 = "#c96765"
good_to_bad_6 = "#c96765"
good_to_bad_7 = "#cf222e"
good_to_bad_8 = "#cf222e"
good_to_bad_9 = "#cf222e"
mode_command_mark = "#000000 #ffffff Bold"
# Not sure where these are used
hex_null = "#000000 #ffffff"
hex_ascii_graphic = "#000000 #ffffff"
hex_ascii_whitespace = "#000000 #ffffff"
hex_ascii_other = "#000000 #ffffff"
hex_non_ascii = "#000000 #ffffff"
staging_area_title = "#000000 #ffffff"
sparse = "#000000 #ffffff"
content_extract = "#000000 #ffffff"
content_match = "#000000 #ffffff"
purpose_normal = "#000000 #ffffff"
purpose_italic = "#000000 #ffffff"
purpose_bold = "#000000 #ffffff"
purpose_ellipsis = "#000000 #ffffff"
file_error = "#000000 #ffffff"
flag_label = "#000000 #ffffff"
flag_value = "#000000 #ffffff"
count = "#000000 #ffffff"
