name: Setup
description: Set up Nix
runs:
  using: "composite"
  steps:
    - uses: canidae-solutions/lix-quick-install-action@8ccd1622179c3881955a55d538670c43e4e22c06 # v5
      with:
        lix_conf: show-trace = true
    - uses: Mic92/hestia@f1f4df2801140a36398ed423533c8460618539df # v3
