name: Setup
description: Install Nix and load the direnv environment
inputs:
  nix-dev-shell:
    description: The name of the Nix devShell to load with direnv
    required: false
    default: ""
  cache-nix-store:
    # SYNC: CACHE_SCOPE
    description: >
      If you set this to "true", the Nix store will be cached at the end of the job
      and restored when this action runs next. Set to "" to disable caching. The
      cache is scoped by workflow, job, and operating system.
    required: false
    default: "true"
  cache-key:
    description: |
      `cache-key` is only used if `cache-nix-store` is "true".

      The `cache-key` is used to identify a cache entry. When a cache entry is saved,
      the `cache-key` is used as its key. When this action is looking for a cache
      entry to restore from, it looks for one whose key matches `cache-key`. In
      other words, a cache entry is considered valid if its key matches `cache-key`.

      It would be difficult to come up with a cache key that perfectly represents
      whether a cache entry is valid. To do so, you would have to keep track of the
      exact set of files that could affect a cache entry, i.e. Nix store, and use the
      checksum of all of these files to create the `cache-key`. And even then it
      wouldn't be perfect since something like adding a comment to one of those files
      would still invalidate the cache, despite not affecting the Nix store. This
      leaves us with two strategies:

        1. We assume a cache entry is invalid more often than it actually is. This
           results in unnecessary pushes of a new cache entry to GitHub Action's
           cache, even though it contains exactly what the old cache entry had. Since
           we restore from the old cache entry on a cache miss, we won't have to pull
           from Nix's cache. We just pull the old cache entry from GHA and push it
           back at the end of the job, except with a different key. One thing to look
           out for is the accumulation of unnecessary store paths in the cache entry.
           This can be mitigated by running garbage collection.
        2. We assume a cache entry is valid more often than it actually is. In this
           case, we will end up having to pull from Nix's cache since the cache entry
           won't have what we need. The problem with this is that we won't create a
           new cache entry with what we just fetched from Nix's cache, since we
           assumed that what we got from GHA was still valid. This means we'll keep
           pulling from Nix's cache without ever updating the GHA cache.

      Based on my observations, pushing to the GHA cache is much faster than pulling
      from the Nix cache so strategy #1 seems better. Below are two ideas for
      implementing strategy #1:

        1. Use something like `hashFiles(<glob>)` where <glob> matches
           any file that could affect the contents of the cache entry i.e. Nix store.
           For example, files that affect which packages are included in the
           `nix-dev-shell`, files that affect their versions, like `flake.lock`,
           files that affect the workflow itself, like this one, or any tasks that
           called in the workflow since they load their dependencies dynamically.
           Getting the exact set of files that could affect the cache is tedious and
           will probably change over time so aim for a superset.
        2. Use the commit hash, `github.sha`. Since the commit hash is usually
           different for every job run, this will probably result in more
           invalidations than the approach above. This approach has the advantage of
           being very simple.

      Valid options for this input are:
        "hashed-files" - See idea #1 above
        "commit-hash" - See idea #2 above
    required: false
    default: commit-hash
runs:
  using: "composite"
  steps:
    # The action run after this, nix-community/cache-nix-action, depends on this
    # specific Nix installer. Though there's an open issue for supporting a different
    # installer: https://github.com/nix-community/cache-nix-action/issues/60
    - uses: nixbuild/nix-quick-install-action@v30
      with:
        nix_conf: |
          # Increase the buffer limit to 124MiB since the buffer would often reach
          # the default limit of 64MiB.
          download-buffer-size = 134217728
          show-trace = true
        # By default this is ${{ github.token }}. This is a problem because the token
        # changes every job run and since this token gets put in the nix.conf, it
        # invalidates cached-nix-shell's cache.
        github_access_token: ""
    - name: Get Year
      id: get-year
      shell: bash
      run: echo "year=$(date '+%Y')" >>"${GITHUB_OUTPUT}"
    - uses: nix-community/cache-nix-action@v6
      id: cache-nix-action
      if: ${{ inputs.cache-nix-store == 'true' }}
      env:
        # The `cache-key` input will be prefixed by this value. This way, cache
        # entries will be scoped by type (nix-store), workflow, job, and operating
        # system.
        #
        # I also added the year to the prefix because otherwise, the `.direnv`
        # directory would continue to grow indefinitely. This happens because on a
        # cache miss, we restore from the most recently accessed cache entry that
        # matches this prefix so we have to avoid accumulating data from old cache
        # entries over time. See the definition of `XDG_CACHE_HOME` further down for
        # what type of data would be in `.direnv`.
        #
        # SYNC: CACHE_SCOPE
        CACHE_KEY_PREFIX: nix-store-${{ steps.get-year.outputs.year }}-${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-
      with:
        paths: |
          # See the definition of `XDG_CACHE_HOME` further down for why this is being
          # cached. See the definition of `CACHE_KEY_PREFIX` for how we prevent this
          # directory from growing indefinitely.
          .direnv
          # By not caching this, only dependencies for shebang scripts executed in
          # _this_ job run will be considered GC roots. In other words, it won't
          # accumulate over time.
          !.direnv/nix-shebang-dependencies
        # The key used to store/restore a cache entry
        primary-key: ${{ env.CACHE_KEY_PREFIX }}${{ inputs.cache-key == 'commit-hash' && github.sha || hashFiles('flake.lock', 'nix/**', '.github/**', 'mise/**') }}
        # If there's a cache miss, restore from the most recently used cache entry
        # with this prefix. In other words, the last cache entry that was used with
        # this job.
        restore-prefixes-first-match: ${{ env.CACHE_KEY_PREFIX }}
        # The combination of the three purge inputs below gives us the following
        # behavior: Delete all cache entries with a key whose prefix is
        # `env.CACHE_KEY_PREFIX`, unless that key is the same as `primary-key`. In
        # other words, we only keep the cache entry created by the current job run
        # and delete all of the older ones.
        purge: true
        purge-primary-key: never
        purge-prefixes: ${{ env.CACHE_KEY_PREFIX }}
        # TODO: Cache entries are only purged if I add these two inputs, but they
        # shouldn't be necessary. I should open an issue.
        purge-created: 0
        purge-last-accessed: 0
        # On a cache miss, we restore from the most recently used cache entry that
        # matches a prefix. Then we possibly add new paths to the Nix store and cache
        # the entire store, including the paths from the old cache entry. This means
        # the Nix store would continue to grow indefinitely. To mitigate this, we'll
        # run garbage collection.
        #
        # I want as much garbage to be collected as possible so I've set it to
        # collect garbage until the store reaches a size of 1 kibibyte or there's no
        # garbage left to collect.
        gc-max-store-size: 1K
    # Composite actions don't support a top-level env key so I'm using GITHUB_ENV
    # instead.
    - name: Set Common Environment Variables
      shell: nix run --file nix/packages.nix bash-script -- {0}
      env:
        NIX_DEV_SHELL: ${{ inputs.nix-dev-shell }}
        NIX_SHEBANG_GC_ROOTS_DIR: ${{ env.GITHUB_WORKSPACE }}/.direnv/nix-shebang-dependencies
        # This way, any programs launched within the direnv environment will store
        # their cache in the direnv layout directory. That entire directory will then
        # be cached in CI, along with the Nix store. Examples of what will be in the
        # cache:
        #   - Any scripts direnv fetches when `source_url` is used e.g. nix-direnv
        #   - nix-direnv's cache
        #   - cached-nix-shell's cache
        #   - Nix's flake evaluation cache
        XDG_CACHE_HOME: ${{ env.GITHUB_WORKSPACE }}/.direnv/xdg-cache-home
      run: |
        echo "NIX_DEV_SHELL=$NIX_DEV_SHELL" >>"$GITHUB_ENV"
        echo "NIX_SHEBANG_GC_ROOTS_DIR=$NIX_SHEBANG_GC_ROOTS_DIR" >>"$GITHUB_ENV"
        echo "XDG_CACHE_HOME=$XDG_CACHE_HOME" >>"$GITHUB_ENV"
    # We shouldn't use the dev shell in the nix-direnv cache when we restore
    # from a prefix-matched cache entry on a cache miss. Since we missed the
    # cache, we can't be sure that the dev shell is still valid.
    - name: Invalidate the nix-direnv Cache
      if: ${{ steps.cache-nix-action.outputs.hit-first-match == 'true' }}
      shell: nix run --file nix/packages.nix bash-script -- {0}
      run: nix-shell direnv/direnv-wrapper.bash direnv/ci.bash exec . direnv-reload
    - name: Load the direnv Environment
      shell: nix run --file nix/packages.nix bash-script -- {0}
      run: |
        nix-shell direnv/direnv-wrapper.bash direnv/ci.bash \
          export gha >> "$GITHUB_ENV"
        # TODO: Setting the PATH with GITHUB_ENV doesn't work[1].
        #
        # [1]: https://github.com/actions/toolkit/issues/655
        nix-shell direnv/direnv-wrapper.bash direnv/ci.bash \
          exec . bash -c 'echo "$PATH"' >> "$GITHUB_PATH"
