name: Setup
description: Install Nix, configure the cache(s), and load a devShell.
inputs:
  dev-shell:
    description: The name of the devShell to activate
    required: false
    default: ci
  cachix-auth-token:
    description: An authentication token for Cachix
    required: true
  use-magic-nix-cache:
    description: Use Magic Nix Cache
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    # In other workflows I use Bash plus some other command-line tools. Since I can't
    # use Nix here to get them, I'll go with Python since operating systems can come
    # with different implementations of the same command-line tool that work
    # differently.
    - shell: python
      id: get-platform
      run: |
        import os
        os_info = os.uname()
        platform = os_info.machine + '-' + os_info.sysname.lower()

        with open(os.environ['GITHUB_OUTPUT'], 'a') as file_handle:
            print(f'platform={platform}', file=file_handle)
    # TODO: Renovate won't manage this action's version until the following is
    # resolved:
    # https://github.com/renovatebot/renovate/issues/28016
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        # SYNC: SYS_CONF_PUBLIC_KEYS SYS_CONF_SUBS
        # ^ With the exception of Cachix, since the Cachix action adds the
        # subsituter.
        extra-conf: |
          extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
          extra-substituters = https://nix-community.cachix.org
        # Use the same version of nix as the one used in this flake. Not only is this
        # good for consistency, but it also ensures that the nix installed here will
        # be able to parse my flake registry.json. The version number is updated
        # automatically, see the lefthook configuration.
        nix-package-url: https://releases.nixos.org/nix/nix-2.24.8/nix-2.24.8-${{ steps.get-platform.outputs.platform }}.tar.xz
    # TODO: This cache shouldn't be enabled for packages that only get used in CI,
    # but since I usually hit the rate limit for the GitHub Action cache, I use this
    # as a backup.
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: bigolu
        authToken: "${{ inputs.cachix-auth-token }}"
    - if: inputs.use-magic-nix-cache == 'true'
      # TODO: Renovate won't manage this action's version until the following is
      # resolved:
      # https://github.com/renovatebot/renovate/issues/28016
      uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        # Cache everything
        upstream-cache: https://null.com
        use-flakehub: false
    - run: nix run --inputs-from . nix-develop-gha# -- .#${{ inputs.dev-shell }}
      shell: bash
