name: Setup
description: Set up Nix
runs:
  using: "composite"
  steps:
    - uses: canidae-solutions/lix-quick-install-action@8ccd1622179c3881955a55d538670c43e4e22c06 # v5
      with:
        lix_conf: show-trace = true
    - uses: Mic92/hestia@dfed9ced335d28978ba74e513939a10db1f71025 # v3
