name: Setup
description: Install Nix, configure the cache(s), and load a devShell.
inputs:
  dev-shell:
    description: The name of the devShell to activate
    required: false
    default: ci
  cachix-auth-token:
    description: An authentication token for Cachix
    required: true
runs:
  using: "composite"
  steps:
    # TODO: Renovate won't manage this action's version until the following is
    # resolved:
    # https://github.com/renovatebot/renovate/issues/28016
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        # SYNC: SYS_CONF_PUBLIC_KEYS SYS_CONF_SUBS
        # ^ With the exception of Cachix, since the Cachix action adds the
        # subsituter.
        extra-conf: |
          extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
          extra-substituters = https://nix-community.cachix.org
    # TODO: This cache shouldn't be enabled for packages that only get used in CI,
    # but since I usually hit the rate limit for the GitHub Action cache, I use this
    # as a backup.
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: bigolu
        authToken: "${{ inputs.cachix-auth-token }}"
    # TODO: Renovate won't manage this action's version until the following is
    # resolved:
    # https://github.com/renovatebot/renovate/issues/28016
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        # Cache everything
        upstream-cache: https://null.com
        use-flakehub: false
    - run: nix run .#nix-develop-gha -- .#${{ inputs.dev-shell }}
      shell: bash
