name: Setup
description: Install Nix, configure the cache, and load direnv.
inputs:
  dev-shell:
    description: The name of the devShell to activate
    required: false
    default: ""
  cachix-auth-token:
    description: >
      An authentication token for Cachix. Only necessary for pushing to the cache.
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      with:
        # Use this until a new version of the action is released with nix v2.24.12+
        install_url: https://releases.nixos.org/nix/nix-2.25.3/install
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: bigolu
        authToken: "${{ inputs.cachix-auth-token }}"
        skipPush: "${{ inputs.cachix-auth-token == '' && 'true' || 'false' }}"
    - shell: nix run --file nix/flake-package-set.nix -- ci-bash {0}
      env:
        DEV_SHELL: ${{ inputs.dev-shell }}
      run: |
        ./scripts/direnv.bash export gha >> "$GITHUB_ENV"
        # GitHub Actions handles the PATH differently
        ./scripts/direnv.bash exec . bash -c 'echo "$PATH"' >> "$GITHUB_PATH"
