name: Setup
description: Install Nix and load direnv.
inputs:
  direnv-dev-shell:
    description: The name of the devShell to activate
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@91a071959513ca103b54280ac0bef5b825791d4d # v31
      with:
        extra_nix_config: |
          # Increase the buffer limit to 124MiB since the buffer would often reach
          # the default limit of 64MiB.
          download-buffer-size = 134217728
          show-trace = true
    - shell: nix run --file nix/flake-package-set.nix -- bash-script {0}
      env:
        DIRENV_DEV_SHELL: ${{ inputs.direnv-dev-shell }}
      run: |
        ./direnv/direnv-wrapper.bash direnv/ci.bash \
          export gha >> "$GITHUB_ENV"
        # GitHub Actions handles the PATH differently
        ./direnv/direnv-wrapper.bash direnv/ci.bash \
          exec . bash -c 'echo "$PATH"' >> "$GITHUB_PATH"
