name: Setup
description: Install Nix, configure the cache(s), and load a devShell.
inputs:
  dev-shell:
    description: The name of the devShell to activate
    required: false
    default: ci
  cachix-auth-token:
    description: An authentication token for Cachix
    required: true
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    # TODO: This cache shouldn't be enabled for packages that only get used in CI,
    # but since I hit the rate-limit a lot for magic-nix-cache, I need to have
    # this as a backup.
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: bigolu
        authToken: "${{ inputs.cachix-auth-token }}"
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        # Cache everything
        upstream-cache: https://null.com
        use-flakehub: false
    - run: nix run .#nix-develop-gha -- .#${{ inputs.dev-shell }}
      shell: bash
