name: Setup
description: Install Nix, configure the cache(s), and load direnv.
inputs:
  dev-shell:
    description: The name of the devShell to activate
    required: false
    default: ci
  cachix-auth-token:
    description: An authentication token for Cachix
    required: true
  use-magic-nix-cache:
    description: Use Magic Nix Cache
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    # TODO: Renovate won't manage this action's version until the following is
    # resolved:
    # https://github.com/renovatebot/renovate/issues/28016
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        # SYNC: SYS_CONF_PUBLIC_KEYS
        # ^ With the exception of Cachix, since the Cachix action adds the
        # subsituter.
        extra-conf: extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
        # Use the same version of nix as the one used in this flake. Not only is this
        # good for consistency, but it also ensures that the nix installed here will
        # be able to parse my flake registry.json. The version number is updated
        # automatically, see the lefthook configuration.
        nix-package-url: https://releases.nixos.org/nix/nix-2.24.9/nix-2.24.9-x86_64-${{ runner.os == 'Linux' && 'linux' || 'darwin' }}.tar.xz
    # TODO: This cache shouldn't be enabled for packages that only get used in CI,
    # but since I usually hit the rate limit for the GitHub Action cache, I use this
    # as a backup.
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: bigolu
        authToken: "${{ inputs.cachix-auth-token }}"
    - if: inputs.use-magic-nix-cache == 'true'
      # TODO: Renovate won't manage this action's version until the following is
      # resolved:
      # https://github.com/renovatebot/renovate/issues/28016
      uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        # Cache everything
        upstream-cache: https://null.com
        use-flakehub: false
    - uses: HatsuneMiku3939/direnv-action@v1
      env:
        NIX_DEV_SHELL: ${{ inputs.dev-shell }}
