name: Setup
description: Install Nix, configure the cache(s), and load a direnv environment
inputs:
  direnv-environment:
    description: The name of the direnv environment to activate
    required: true
  cachix-auth-token:
    description: An authentication token for Cachix
    required: true
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: bigolu
        authToken: "${{ inputs.cachix-auth-token }}"
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        # Cache everything
        upstream-cache: https://null.com
        use-flakehub: false
    - run: nix run github:nicknovitski/nix-develop -- ${{ inputs.direnv-environment }}
      shell: bash
