name: Setup
description: Set up Nix
runs:
  using: "composite"
  steps:
    # The action run after this, nix-community/cache-nix-action, depends on this
    # specific Nix installer. Though there's an open issue for supporting a different
    # installer: https://github.com/nix-community/cache-nix-action/issues/60
    - uses: nixbuild/nix-quick-install-action@1f095fee853b33114486cfdeae62fa099cda35a9 # v33
      with:
        nix_conf: |
          show-trace = true
          # This way, if we fail to build something, we can make its derivation a GC
          # root and the derivation's dependencies won't get garbage collected. Since
          # they won't get garbage collected, they'll be cached and we won't lose our
          # build progress.
          #
          # There's an issue[1] for automating the creation of the derivation GC root.
          #
          # [1]: https://github.com/NixOS/nix/issues/7561
          keep-outputs = true
          # This will save a lot of space since we also enabled `keep-outputs`.
          keep-derivations = false
    - uses: nix-community/cache-nix-action/restore@135667ec418502fa5a3598af6fb9eb733888ce6a # v6
      with:
        # SYNC: cache-settings-nix
        #
        # We don't know what suffix the key will have so we'll never get a primary
        # key match.
        primary-key: will-not-match
        restore-prefixes-first-match: nix-${{ github.ref_name }}-${{ github.workflow }}-${{ github.job }}-${{ runner.arch }}-${{ runner.os }}-
        paths: |
          ~/.cache/gc-roots
