---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mattn/efm-langserver/master/schema.json
tools:
  action-lint: &action-lint
    lint-command: >
      env input=${INPUT} substr=.github/workflows sh -c
      '[ "${input#*$substr}" != "$input" ] &&
      actionlint -no-color -
      $([ -f .github/actionlint.yaml ] && echo "-config-file .github/actionlint.yaml")
      $([ -f .github/actionlint.yml ] && echo "-config-file .github/actionlint.yml")'
    lint-source: "action-lint"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c:%m"
  yamllint: &yamllint
    lint-command: "yamllint --strict --format parsable -"
    lint-source: "yamllint"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: [%t%*[a-z]] %m"
  markdownlint-cli2: &markdownlint-cli2
    lint-command: "markdownlint-cli2 ${INPUT}"
    lint-source: "markdownlint-cli2"
    lint-stdin: false
    lint-formats:
      - "%f:%l:%c: %m"
      - "%f:%l:%c %m"
      - "%f:%l: %m"
      - "%f:%l %m"
  desktop-file-validate: &desktop-file-validate
    lint-command: bash -c '[[ ${INPUT} = *.desktop ]] && desktop-file-validate ${INPUT}'
    lint-source: "desktop-file-validate"
    lint-stdin: false
    lint-formats:
      - "%f: %m"
  config-file-validator: &config-file-validator
    lint-command: validator -groupby pass-fail ${INPUT}
    lint-source: "config-file-validator"
    lint-stdin: false
    lint-formats:
      - "%A    × %f"
      - "%Z        error: Error at line %l column %c: %m"
      - "%A    × %f"
      - "%Z        error: %m"
  typos: &typos
    lint-command: typos --color never --format brief ${INPUT}
    lint-source: typos
    lint-stdin: false
    lint-severity: 2
    lint-formats:
      - "%f:%l:%c: %m"
  committed: &committed
    lint-after-open: true
    lint-command: committed --color never --format brief --commit-file ${INPUT}
    lint-source: committed
    lint-stdin: false
    lint-severity: 2
    lint-formats:
      - "%f: error %m"

version: 2
root-markers:
  - .git/
lint-debounce: 1s
languages:
  yaml:
    - <<: *action-lint
    - <<: *yamllint
  markdown:
    - <<: *markdownlint-cli2
  editorconfig:
    - <<: *config-file-validator
  ini:
    - <<: *config-file-validator
  git-commit:
    - <<: *committed
  git-rebase:
    - <<: *committed
  =:
    - <<: *desktop-file-validate
    - <<: *typos
