#:schema https://json.schemastore.org/prettierrc

[[overrides]]
files = [
  "*.jsonc",
  # These files also contain JSONC
  ".vscode/*.json",
  "renovate.json",
]
[overrides.options]
# Technically, we don't need to set this for files that match the `*.jsonc`
# pattern since they will already use the `jsonc` parser. We do it anyway so we
# can keep all the options for files containing JSONC in the same place.
parser = "jsonc"
# While there's no official specification for JSONC, there's a draft which
# states that some JSONC parsers may not have support for trailing commas[1]. To
# be safe, we won't use them. There's an open issue to have prettier stop adding
# trailing commas[2].
#
# [1]: https://jsonc.org/#:~:text=Trailing%20commas
# [2]: https://github.com/prettier/prettier/issues/15956
trailingComma = "none"

[[overrides]]
files = ["*.md"]
[overrides.options]
proseWrap = "always"
