[global]
excludes = [
  "*.gitkeep",
  "*.lock",
  "*.jsonc",
  "*.toml",
  "*.txt",
  ".git-hook-assets/actions/*",
  "dotfiles/*",
  ".editorconfig",
  ".gitignore",
  ".ignore",
  ".shellcheckrc",
  "flake-modules/bundler/gozip/go.mod",
  "flake-modules/bundler/gozip/go.sum",

  # TODO: just's builtin formatter shifts aroung my comments so I'm not using
  # it. I should file a report since they may not be aware of this.
  #
  # I would just comment out the just formatter, but then treefmt would
  # warn me that any files that would have been formatted by it have not
  # formatter. Instead, I'll ignore the files.
  ".justfile",
  "ci.just",
]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.js", "*.json", "*.json5", "*.md", "*.yml",]

[formatter.sh]
command = "shfmt"
options = ["--write",]
includes = [
  ".github/run.sh"
]

[formatter.bash]
command = "shfmt"
options = ["--write",]
includes = [".envrc", "*.bash",]

# TODO: Doesn't adhere to the treefmt spec for formatters in that it
# unconditionally writes to input files, even if everything is formatted
# correctly.
#
# It's fixed on master, but will be part of the release for v4.0
[formatter.fish]
command = "fish_indent"
options = ["--write",]
includes = ["*.fish",]

[formatter.nix-deadnix]
priority = 0
command = "deadnix"
options = ["--edit"]
includes = [ "*.nix" ]

[formatter.nix-statix]
priority = 1
command = "bash"
options = [
    "-euc",
    """
# statix doesn't support passing multiple files yet:
# https://github.com/nerdypepper/statix/issues/69
for file in "$@"; do
  statix fix "$file"
done
    """,
    "--",
]
includes = [ "*.nix" ]

[formatter.nix-alejandra]
priority = 2
command = "alejandra"
includes = [ "*.nix" ]

[formatter.justfile]
command = "just"
options = ["--unstable", "--fmt", "--justfile",]
includes = [".justfile",]

[formatter.lua]
command = "stylua"
includes = ["*.lua",]

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.python]
command = "black"
includes = ["*.py"]
