extends: default

rules:
  document-start: disable
  truthy: disable

  # Disable style related lints, prettier will handle that
  braces: disable
  brackets: disable
  colons: disable
  comments-indentation: disable
  comments: disable
  empty-lines: disable
  hyphens: disable
  indentation: disable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: disable
  trailing-spaces: disable
