[default]
extend-words.iterm = "iterm"

[type.yaml]
extend-glob = ["dotfiles/lsd/icons.yaml"]
[type.yaml.extend-words]
styl = "styl"

# TODO: There's an open issue for adding file types to typos for git's files, like
# the commit file.
#
# [1]: https://github.com/crate-ci/typos/issues/1117
[type.gitcommit]
extend-glob = ["COMMIT_EDITMSG"]
extend-ignore-re = [
  # Ignore the diff that's added to a commit file if `git commit --verbose` is used
  '(?sm)^# ------------------------ >8 ------------------------$.*',
  # Ignore commented lines
  '(?m)^#.*$',
]
