[default]
extend-words.iterm = "iterm"
extend-ignore-re = [
  # TODO: This way, I can have typos ignore lines by adding the comment `#
  # typos:ignore` to the end of the line. There's an open issue for supporting inline
  # exclusions[1].
  #
  # [1]: https://github.com/crate-ci/typos/issues/316
  "(?Rm)^.*(#|//)\\s*typos:ignore$",
]

# TODO: There's an open issue for adding file types to typos for git's files, like
# the commit file.
#
# [1]: https://github.com/crate-ci/typos/issues/1117
[type.gitcommit]
extend-glob = ["COMMIT_EDITMSG"]
extend-ignore-re = [
  # Ignore the diff that's added to a commit file if `git commit --verbose` is used
  '(?sm)^# ------------------------ >8 ------------------------$.*',
  # Ignore commented lines
  '(?m)^#.*$',
]
