[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=default_save_path
Session\ExcludedFileNames=
Session\GlobalMaxSeedingMinutes=25200
Session\MaxActiveDownloads=100
Session\MaxActiveTorrents=100
Session\MaxActiveUploads=100
Session\QueueingEnabled=true
Session\QueueingSystemEnabled=true
Session\ShareLimitAction=RemoveWithContent

[Core]
AutoDeleteAddedTorrentFile=Never

[Preferences]
WebUI\Port=8199

[Meta]
MigrationVersion=8
