[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=default_save_path
Session\ExcludedFileNames=
Session\QueueingEnabled=true
Session\QueueingSystemEnabled=false

[Core]
AutoDeleteAddedTorrentFile=Never

[Preferences]
WebUI\Port=8199

[Meta]
MigrationVersion=8
