[settings]
# This avoids an untracked dependency on /usr/bin/env which would have been used
# in a shebang. It also allows us to centralize the file interpreter.
use_file_shell_for_executable_tasks = true
unix_default_file_shell_args = "nix-script"
quiet = true
# Some tasks need stdin for things like sudo password prompts
raw = true
