[settings]
# I prefer this to shebangs for these reasons:
#   - Avoids an untracked dependency on `/usr/bin/env`, which would have beeen
#     used in the shebang.
#   - I only have to specify the file interpreter once instead of once per
#     shebang.
#   - Shebangs don't work on Windows.
use_file_shell_for_executable_tasks = true
unix_default_file_shell_args = "nix-scene"
quiet = true
# Some tasks need stdin for things like sudo password prompts
raw = true
