[settings]
# This avoids a dependency on /usr/bin/env which would have been used in a shebang
use_file_shell_for_executable_tasks = true
unix_default_file_shell_args = "cached-nix-shell"
quiet = true
# Some tasks need stdin for things like sudo password prompts
raw = true
