# TODO: Consider upstreaming. This way nix-darwin configures the PATH for the
# login shell the same way system-manager does. In fact, it should probably set
# XDG_DATA_DIRS too, see what system-manager does.

{ pkgs, lib, ... }:
let

  script =
    let
      inherit (lib) escapeShellArg makeBinPath;

      file = "/etc/zprofile";
      marker = "configureLoginShell";
      line = ''export PATH="/run/current-system/sw/bin:$PATH"'';
    in
    ''
      OLD_PATH="$PATH"
      PATH="${
        makeBinPath (
          with pkgs;
          [
            coreutils
            gnugrep
          ]
        )
      }:$PATH"

      touch ${file}
      if ! grep '${marker}' ${file} > /dev/null; then
        # shellcheck disable=2016
        printf '\n%s\n' ${escapeShellArg line}' # generated by nix-darwin: ${marker}' |
          tee -a ${file}
      fi

      PATH="$OLD_PATH"
    '';
in
{
  config = {
    system.activationScripts.configureLoginShell.text = script;

    # Reapply the changes if they get removed, which can happen during a macOS
    # update due to its immutable base system. Adapted from nix-darwin[1].
    #
    # [1]: https://github.com/nix-darwin/nix-darwin/blob/230a197063de9287128e2c68a7a4b0cd7d0b50a7/modules/services/activate-system/default.nix#L20
    launchd.daemons.restore-profile-changes = {
      serviceConfig = {
        RunAtLoad = true;
        KeepAlive.SuccessfulExit = false;
      };

      script = ''
        set -o errexit
        set -o pipefail
        ${script}
      '';
    };
  };
}
