schema = 3

[mod]
  [mod."github.com/deepakjois/gousbdrivedetector"]
    version = "v0.0.0-20240702044807-c8f9c0587c5e"
    hash = "sha256-c9u+sj5NHZyaw6v7pfCn74tqiml/9YXJD9eiXvie4IU="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.11"
    hash = "sha256-LFSIWy0C4VbiuPve0eKHr7Q7s4XtaGzsZ3qpO+6bEgc="
  [mod."github.com/mitchellh/colorstring"]
    version = "v0.0.0-20190213212951-d06e56a500db"
    hash = "sha256-dg5havre+NkxU85tbWXgdhjVtVnkNfTVa999HX+JVbQ="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/schollz/progressbar/v3"]
    version = "v3.17.1"
    hash = "sha256-cGI2k1a+e2kRq/SCR2EDdDMBlauP3JFLQtT6c5HPU+Q="
  [mod."golang.org/x/sync"]
    version = "v0.10.0"
    hash = "sha256-HWruKClrdoBKVdxKCyoazxeQV4dIYLdkHekQvx275/o="
  [mod."golang.org/x/sys"]
    version = "v0.28.0"
    hash = "sha256-kzSlDo5FKsQU9cLefIt2dueGUfz9XuEW+mGSGlPATGc="
  [mod."golang.org/x/term"]
    version = "v0.27.0"
    hash = "sha256-cb5p/yOlVL7dbkxugUVfqESTVpZ2LtrUWPnx9yue3r0="
