name: Get Bot Token
description: Get an auth token from our bot
inputs:
  bot-private-key:
    description: The private key for the bot. You can find it in the settings page for its app.
    required: true
outputs:
  token:
    description: "An auth token from the bot"
    value: ${{ steps.bigolu-bot-app-token.outputs.token }}
runs:
  using: "composite"
  steps:
    - uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
      id: bigolu-bot-app-token
      with:
        app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
        private-key: ${{ inputs.bot-private-key }}
