name: Set Up Nix
description: Install Nix, configure the cache(s), and load a devshell
inputs:
  devshell-name:
    description: The name of the devShell to load
    required: true
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: bigolu
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        # Cache everything
        upstream-cache: https://null.com
        use-flakehub: false
    - uses: nicknovitski/nix-develop@v1
      with:
        arguments: .#${{ inputs.devshell-name }}
