name: Save Cache
description: Save cache
runs:
  using: "composite"
  steps:
    - id: should-save
      shell: bash-script {0}
      run: |
        old="$HOME/.cache/store-paths"

        temp="$(mktemp)"
        for symlink in /nix/var/nix/gcroots/auto/*; do
          if [[ -e $symlink ]]; then
            realpath "$symlink" >>"$temp"
          fi
        done
        new="$(mktemp)"
        sort "$temp" >"$new"

        if [[ ! -e $old || $(<"$old") != $(<"$new") ]]; then
          echo 'should-save=true' >>"$GITHUB_OUTPUT"

          if [[ -e $old ]]; then
            echo '::group::Store paths diff'
            echo 'Added paths:'
            comm -13 "$old" "$new"
            echo
            echo 'Removed paths:'
            comm -23 "$old" "$new"
            echo '::endgroup::'
          else
            echo 'Old cache did not exist'
          fi

          cp "$new" "$old"

          # Run garbage collection to stop the nix store from growing indefinitely.
          # This can happen because on a cache miss, we restore from the most recently
          # used cache entry so we have to avoid accumulating data from old cache
          # entries over time.
          echo '::group::Garbage collection logs'
          nix-collect-garbage --delete-old
          echo '::endgroup::'
        else
          echo 'should-save=false' >>"$GITHUB_OUTPUT"
        fi
    - if: steps.should-save.outputs.should-save == 'true'
      uses: nix-community/cache-nix-action/save@v6
      with:
        primary-key: ${{ env.SETUP_PRIMARY_KEY }}
        paths: ${{ env.SETUP_PATHS }}
        purge: true
        purge-primary-key: always
