name: Save Cache
description: Save cache
runs:
  using: "composite"
  steps:
    - id: pre-nix-cache-save
      shell: bash-script {0}
      run: |
        old="$HOME/.cache/gc-roots"

        new="$(mktemp)"
        {
          # We only want extant symlink destinations to be printed, but we don't want
          # realpath to exit with a non-zero code if it encounters a broken symlink
          # since that would cause the script to exit.
          set +o errexit
          realpath --quiet --canonicalize-existing /nix/var/nix/gcroots/auto/*
          set -o errexit
        } |
          # `comm` requires input files to be sorted
          sort >"$new"

        if [[ -e $old && $(<"$old") == $(<"$new") ]]; then
          echo 'should-save=false' >>"$GITHUB_OUTPUT"
          exit
        else
          echo 'should-save=true' >>"$GITHUB_OUTPUT"
        fi

        if [[ -e $old ]]; then
          echo '::group::GC roots diff'
          echo 'Added roots:'
          comm --nocheck-order -13 "$old" "$new"
          echo
          echo 'Removed roots:'
          comm --nocheck-order -23 "$old" "$new"
          echo '::endgroup::'
        else
          echo 'Old cache did not exist'
        fi

        echo '::group::All new roots'
        cat "$new"
        echo '::endgroup::'

        # Run garbage collection to stop the nix store from growing indefinitely.
        # This can happen because on a cache miss, we restore from the most recently
        # used cache entry so we have to avoid accumulating data from old cache
        # entries over time.
        echo '::group::Garbage collection logs'
        nix-collect-garbage --delete-old
        echo '::endgroup::'

        # Delete these directories for the same reason as above.
        #
        # TODO: I don't even want to cache these directories in the first place,
        # they're added by default by cache-nix-action. I tried to remove them by
        # adding `!<path>` the `paths` inputs, but it didn't work which I think is
        # because of this issue[1]. On one of my workflows, these directories were
        # ~200 MB so removing them saves a lot of space.
        #
        # [1]: https://github.com/actions/toolkit/issues/713
        rm -rf ~/.cache/nix
        sudo rm -rf ~root/.cache/nix

        cp "$new" "$old"

        key="$(sha256sum "$new" | cut --delimiter ' ' -f1)"
        echo "$key" >~/.cache/nix-last-key
        echo "key=$key" >>"$GITHUB_OUTPUT"
    - if: steps.pre-nix-cache-save.outputs.should-save == 'true'
      uses: nix-community/cache-nix-action/save@135667ec418502fa5a3598af6fb9eb733888ce6a # v6
      with:
        purge: true
        purge-primary-key: always
        # SYNC: cache-settings-nix-last-key
        nix: false
        primary-key: nix-last-key-${{ github.workflow }}-${{ github.job }}-${{ runner.arch }}-${{ runner.os }}-${{ github.ref_name }}
        paths: |
          ~/.cache/nix-last-key
    - if: steps.pre-nix-cache-save.outputs.should-save == 'true'
      uses: nix-community/cache-nix-action/save@135667ec418502fa5a3598af6fb9eb733888ce6a # v6
      with:
        # SYNC: cache-settings-nix
        primary-key: nix-${{ steps.pre-nix-cache-save.outputs.key }}
        paths: |
          ~/.cache/gc-roots
