name: Check style
description: Check style
inputs:
  github-token:
    description: The name of the devShell to activate
    required: false
    default: ci
  cachix-auth-token:
    description: An authentication token for Cachix
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - uses: ./.github/actions/setup
      with:
        dev-shell: ciCheckStyle
        cachix-auth-token: "${{ inputs.cachix-auth-token }}"
    - shell: bash
      run: lefthook run format --all-files
    - uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
      with:
        tool_name: code-style
        level: error
        filter_mode: nofilter
        reviewdog_flags: "-fail-level=any"
        github_token: ${{ inputs.github-token }}
