name: Lint
description: Lint
inputs:
  github-token:
    description: The name of the devShell to activate
    required: false
    default: ci
  cachix-auth-token:
    description: An authentication token for Cachix
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - uses: ./.github/actions/setup
      with:
        dev-shell: ciLint
        cachix-auth-token: "${{ inputs.cachix-auth-token }}"
    - shell: bash
      run: |
        if ! lefthook run --all-files fix-lint; then
          echo 'DID_FAIL=true' >> "$GITHUB_ENV"
        fi
    - uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
      with:
        tool_name: lint-autofix
        level: error
        filter_mode: nofilter
        reviewdog_flags: "-fail-level=any"
        github_token: ${{ inputs.github-token }}
    - shell: bash
      env:
        # 'lint check' calls reviewdog so it needs a token
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
      run: |
        if ! lefthook run --all-files check-lint; then
          echo 'DID_FAIL=true' >> "$GITHUB_ENV"
        fi
    # By waiting until everything has run to fail the job, we'll see all the
    # errors at once instead of fixing some errors, rerunning the job, and
    # finding more.
    - shell: bash
      if: ${{ env.DID_FAIL == 'true' }}
      run: exit 1
