[global]
  warn_timeout = "1h"
  load_dotenv = true
  strict_env = true
  hide_env_diff = true

[whitelist]
  prefix = [
    "~/code/system-configurations",
    "~/code/bigolu.github.io",
    "~/code/practice",
  ]
