schema = 3
cachePackages = [
  'github.com/klauspost/compress',
  'github.com/klauspost/compress/fse',
  'github.com/klauspost/compress/huff0',
  'github.com/klauspost/compress/zstd',
  'github.com/mitchellh/colorstring',
  'github.com/rivo/uniseg',
  'github.com/schollz/progressbar/v3',
  'golang.org/x/sync/errgroup',
  'golang.org/x/sync/semaphore',
  'golang.org/x/sys/unix',
  'golang.org/x/term'
]

[mod]
  [mod.'github.com/klauspost/compress']
    version = 'v1.18.6'
    hash = 'sha256-gULc+A2Clg2HnwR9UNXSIHVGdFY/aGqhf0zlvMxqaSY='

  [mod.'github.com/mitchellh/colorstring']
    version = 'v0.0.0-20190213212951-d06e56a500db'
    hash = 'sha256-dg5havre+NkxU85tbWXgdhjVtVnkNfTVa999HX+JVbQ='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/schollz/progressbar/v3']
    version = 'v3.19.0'
    hash = 'sha256-ABW5J1C0XgtVYV+7N6g6/ZGMKOzF4iingBS7ruvO5S8='

  [mod.'golang.org/x/sync']
    version = 'v0.20.0'
    hash = 'sha256-ybcjhCfK6lroUM0yswUvWooW8MOQZBXyiSqoxG6Uy0Y='

  [mod.'golang.org/x/sys']
    version = 'v0.43.0'
    hash = 'sha256-aDQXqSTZES2l/132PBxhZN4ywldpPyfm7LByYCHzzwM='

  [mod.'golang.org/x/term']
    version = 'v0.42.0'
    hash = 'sha256-FCiDvAfq7dgBGQuiDYDFJbj/JPawhrmPF2qdUEftQ1c='
