name: Ensure generated code is up to date
description: Ensure generated code is up to date
inputs:
  github-token:
    description: GitHub token
    required: true
  cachix-auth-token:
    description: Cachix auth token
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup
      with:
        dev-shell: ciCodegen
        cachix-auth-token: "${{ inputs.cachix-auth-token }}"
    - shell: bash
      run: |
        # This step shouldn't fail because if it does, reviewdog will never run.
        # By using a conditional, Bash won't fail if this command fails.
        if ! lefthook run generate --all-files; then
          # reviewdog only fails if files were changed. That means if lefthook fails, but
          # doesn't change any files, the job would still pass. By setting this
          # variable we can communicate a failure even when files don't change.
          echo 'CODEGEN_FAILED=true' >> "$GITHUB_ENV"
        fi
    - uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
      with:
        tool_name: code-generation
        level: error
        filter_mode: nofilter
        reviewdog_flags: "-fail-level=any"
        github_token: ${{ inputs.github-token }}
    - if: ${{ env.CODEGEN_FAILED == 'true' }}
      run: exit 1
      shell: bash
