name: Cache Build Results
on:
  push:
    paths:
      - ".github/workflows/cache-build-results.yml"
      - "flake.nix"
      - "flake.lock"
      - "flake-modules/**"
      - "dotfiles/**"
jobs:
  add-to-cachix:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest uses M1 so I'll just use the most recent version of macOS
        # that they still on run intel macs
        os: [ubuntu-latest, macos-13]
      fail-fast: false
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: bigolu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: NIXPKGS_ALLOW_UNFREE=1 nix run --show-trace .#nix -- build --impure --show-trace
