name: Check for Broken Links
on:
  workflow_dispatch:
  schedule:
    # Once a week
    - cron: "0 0 * * 0"
concurrency:
  # Since we are only interested in checking links for the latest commit to
  # the branch, we will limit the workflow to running at most once per branch,
  # cancelling older runs when newer ones start.
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  check-for-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/setup
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          dev-shell: ciCheckForBrokenLinks
      - id: bot-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@7cd0af4c74a61395d455af97419279d86aafaede # v2
        with:
          # To avoid being rate-limited by GitHub
          token: "${{ steps.bot-token.outputs.token }}"
          args: "--verbose --no-progress ."
      - if: env.lychee_exit_code != 0
        run: |
          gh issue create \
            --title 'Link Checker Report' \
            --body-file ./lychee/out.md \
            --label report \
            --label 'automated issue'
