name: Check for Broken Links
on:
  workflow_dispatch:
  schedule:
    # Once a week
    - cron: "0 0 * * 0"
jobs:
  check-for-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: bigolu-bot-app-token
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          # To avoid being rate-limited by GitHub
          token: "${{ steps.bigolu-bot-app-token.outputs.token }}"
          args: "--verbose --no-progress ."
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
