name: Checked for Leaked Secrets
on:
  # Normally I'd ignore the default branch since I don't directly push there,
  # but for this project I do.
  push:
  # TODO: I should set concurrency when the event is pull_request because each
  # run will check all commits in the pull request. This means I can cancel
  # older runs when newer ones start and all commits will still be checked.
  pull_request:
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  check-for-leaked-secrets:
    # Not worried about renovate leaking secrets.
    #
    # For more on how the branch name is calculated see:
    # https://stackoverflow.com/a/71158878
    if: ${{ ! startsWith(github.head_ref || github.ref_name, 'renovate/')  }}
    runs-on: ubuntu-latest
    steps:
      # Shallow clone using the steps from the trufflehog README:
      # https://github.com/trufflesecurity/trufflehog?tab=readme-ov-file#shallow-cloning
      - run: |
          if [ "$EVENT_NAME" == 'push' ]; then
            echo "depth=$(( $(jq length <<< "$COMMITS_JSON") + 2 ))" >> "$GITHUB_ENV"
            echo "branch=$REF_NAME" >> "$GITHUB_ENV"
          elif [ "$EVENT_NAME" == 'pull_request' ]; then
            echo "depth=$(( "$PR_COMMITS" + 2 ))" >> "$GITHUB_ENV"
            echo "branch=$PR_HEAD_REF" >> "$GITHUB_ENV"
          fi
        env:
          EVENT_NAME: ${{ github.event.name }}
          COMMITS_JSON: ${{ toJson(github.event.commits) }}
          REF_NAME: ${{ github.ref_name }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_COMMITS: ${{ github.event.pull_request.commits }}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{env.branch}}
          fetch-depth: ${{env.depth}}
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciLeakedSecrets
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - if: ${{ github.event.name == 'push' }}
        run: bash ./scripts/ci/check-for-leaked-secrets.bash
        env:
          EVENT_NAME: ${{ github.event.name }}
          AFTER: ${{ github.event.after }}
          BEFORE: ${{ github.event.before }}
      - if: ${{ github.event.name == 'pull_request' }}
        run: bash ./scripts/ci/check-for-leaked-secrets.bash
        env:
          EVENT_NAME: ${{ github.event.name }}
          BASE_SHA: ${{github.event.pull_request.base.sha}}
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
