name: "Check Pull Request"
on:
  pull_request:
  push:
    # These branches get merged without a pull request being made so we need to check
    # them too.
    branches:
      # SYNC: AUTOMERGE_PREFIX
      - "renovate/branch-automerge/**"
# Since we're only interested in checking the latest commit to the branch, we could
# limit the workflow to running at most once per branch, cancelling older runs when
# newer ones start. However, doing so would mean if we push to a branch, a
# pull_request event and push event would trigger this workflow and one of those
# workflow runs would be cancelled. This should be fine, but since the jobs in this
# workflow are required checks they must run. Meaning they can't be skipped as a
# result of this concurrency setting. Even if the same workflow is triggered once by
# a push event and once by a pull_request, like with this workflow, the jobs in both
# of them are considered required checks and they all must run. To get around this,
# we instead limit the workflow to running once per event per branch. This way, we
# still only run the on the latest commit, but a required check is never skipped. To
# skip duplicate runs, we instead use a job.<job_id>.if conditional since skipping
# required checks from there is ok.
concurrency:
  # For more information on how the branch name is calculated see:
  # https://stackoverflow.com/a/71158878
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  lint:
    # Only run if both of the following are true:
    #   - It was not triggered by a pull request event for a Renovate automerge
    #     branch. Those are covered by the push event.
    #   - This branch is not a Renovate branch. I don't think a change made by
    #     Renovate will cause a lint issue.
    #
    # For more information on how the branch name, is calculated see:
    # https://stackoverflow.com/a/71158878
    if: ${{ (! (github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/branch-automerge/'))) && (! startsWith(github.head_ref || github.ref_name, 'renovate/')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciLint
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - env:
          # A token is needed to report the errors found by the lint checker.
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: lefthook run check --commands check-lint,fix-lint --all-files
      # The lint command run in the previous step fails if it finds or fixes any lint
      # issues. This causes the step that it's run in to fail as well. If that
      # happens, then by default this step, and all steps after it, wouldn't get run.
      # That means this step wouldn't be able to report the lint issues that were
      # fixed.
      #
      # We could have used `always()` to ensure this step runs, but that would mean
      # even if the workflow was cancelled by a user, this step would still run.
      # Instead, we say only run if the workflow wasn't cancelled. This way, we still
      # have the ability to cancel all the steps in the workflow while also allowing
      # this step to run even if previous ones fail.
      - if: "!cancelled()"
        run: |
          git diff |
          ./scripts/reviewdog.bash \
            -name=fix-lint \
            -f=diff \
            -f.diff.strip=1
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  check-style:
    # Only run this job if both of the following are true:
    #   - It was not triggered by a pull request event for a Renovate automerge
    #     branch. Those are covered by the push event.
    #   - The branch is not a Renovate branch. I don't think a change made by renovate
    #     would break the code style.
    #
    # For more information on how the branch name, is calculated see:
    # https://stackoverflow.com/a/71158878
    if: ${{ (! (github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/branch-automerge/'))) && (! startsWith(github.head_ref || github.ref_name, 'renovate/')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciCheckStyle
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: lefthook run format --all-files
      # The command run in the previous step fails if it formats any code. This
      # causes the step that it's run in to fail as well. If that happens, then by
      # default this step, and all steps after it, wouldn't get run. That means this
      # step wouldn't be able to report the code that got formatted.
      #
      # We could have used `always()` to ensure this step runs, but that would mean
      # even if the workflow was cancelled by a user, this step would still run.
      # Instead, we say only run if the workflow wasn't cancelled. This way, we still
      # have the ability to cancel all the steps in the workflow while also allowing
      # this step to run even if previous ones fail.
      - if: "!cancelled()"
        run: |
          git diff |
          ./scripts/reviewdog.bash \
            -name=code-style \
            -f=diff \
            -f.diff.strip=1
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  ensure-generated-code-is-up-to-date:
    # Only run this job if it wasn't triggered by a pull request event for a Renovate
    # automerge branch. Those are covered by the push event.
    if: ${{ ! (github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/branch-automerge/')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      # Ideally, I'd put this job in a separate workflow and use 'paths:' to match
      # relevant files, but since this check is required, it can't be skipped at the
      # workflow level[1]. A skip using jobs.<job_id>.if would be ok, but you can't
      # use the 'paths:' filter there. Since individual steps are also allowed to be
      # skipped, I decided to use an action that can tell you if certain files were
      # changed. To avoid having to put a conditional on every step I moved all the
      # other steps into a separate action.
      #
      # [1]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
      - name: Get all codegen-related files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@c3a1bb2c992d77180ae65be6ae6c166cf40f857c # v45
        with:
          # SYNC: GENERATOR_PATTERNS
          files_yaml: |
            codegen:
              - "**/go.mod"
              - "**neovim/lua/*.lua"
              - "README.md"
              - "scripts/**"
              - ".envrc"
              - "flake.lock"
              - "flake-modules/**"
              - "flake.nix"
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        uses: ./.github/actions/ensure-generated-code-is-up-to-date
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
