name: Check links
on:
  workflow_dispatch:
  schedule:
    # Run once a month.
    #
    # I've chosen a non-zero minute for the workflow to run to avoid running it at
    # the start of the hour. This is because GitHub sees high load at the start of
    # every hour and when that happens, some queued jobs may be delayed or
    # dropped[1].
    #
    # [1]: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: "43 0 1 * *"
permissions:
  actions: "write"
  issues: "write"
jobs:
  check-links:
    runs-on: ubuntu-24.04
    steps:
      - uses: bigolu/lychee-aio-action@6e5df3f0f6a89030a5c76f5f1502b8444891b642 # main
