name: "Check Pull Request"
on:
  pull_request:
  push:
    branches:
      # SYNC: AUTOMERGE_PREFIX
      - "renovate/branch-automerge/**"
concurrency:
  # Since we're only interested in checking the latest commit to the branch,
  # we'll limit the workflow to running at most once per branch, cancelling
  # older runs when newer ones start.
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  lint:
    runs-on: ubuntu-latest
    steps:
      # I would just put a conditional on the whole job, but since this check is
      # required, it can't be skipped at the job level[1]. However, individual steps
      # can be skipped. To avoid having to put a conditional over every step I moved
      # all the steps into a separate action.
      #
      # [1]:
      # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
      - if: ${{ ! startsWith(github.head_ref || github.ref_name, 'renovate/')  }}
        uses: ./.github/actions/lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  check-style:
    runs-on: ubuntu-latest
    steps:
      # I would just put a conditional on the whole job, but since this check is
      # required, it can't be skipped at the job level[1]. However, individual steps
      # can be skipped. To avoid having to put a conditional over every step I moved
      # all the steps into a separate action.
      #
      # [1]:
      # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
      - if: ${{ ! startsWith(github.head_ref || github.ref_name, 'renovate/')  }}
        uses: ./.github/actions/check-style
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  ensure-generated-code-is-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      # Ideally, I'd put this job in a separate workflow and use 'paths:' to match
      # relevant files, but since this check is required, it can't be skipped at the
      # job or workflow level[1]. However, individual steps can be skipped. To avoid
      # having to put a conditional over every step I moved all the steps into a
      # separate action.
      #
      # [1]:
      # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
      - name: Get all codegen-related files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
        with:
          # SYNC: GENERATOR_PATTERNS
          files_yaml: |
            codegen:
              - "**/go.mod"
              - "**neovim/lua/*.lua"
              - "README.md"
              - "scripts/**"
              - ".envrc"
              - "flake.lock"
              - "flake-modules/**"
              - "flake.nix"
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        uses: ./.github/actions/ensure-generated-code-is-up-to-date
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
