name: "Check Pull Request"
on:
  # It should also run on pushes to the default branch since I push there
  # directly, but I feel like that's a waste of resources.
  pull_request:
concurrency:
  # Since we're only interested in checking the latest commit to the branch,
  # we'll limit the workflow to running at most once per branch, cancelling
  # older runs when newer ones start.
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  lint:
    if: ${{ ! startsWith(github.head_ref, 'renovate/')  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciLint
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: |
          if ! lefthook run --all-files fix-lint; then
            echo 'DID_FAIL=true' >> "$GITHUB_ENV"
          fi
      - uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
        with:
          tool_name: lint-autofix
          level: error
          filter_mode: nofilter
          reviewdog_flags: "-fail-level=any"
      - env:
          # 'lint check' calls reviewdog so it needs a token
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! lefthook run --all-files check-lint; then
            echo 'DID_FAIL=true' >> "$GITHUB_ENV"
          fi
      # By waiting until everything has run to fail the job, we'll see all the
      # errors at once instead of fixing some errors, rerunning the job, and
      # finding more.
      - if: ${{ env.DID_FAIL == 'true' }}
        run: exit 1
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  check-style:
    if: ${{ ! startsWith(github.head_ref, 'renovate/')  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciCheckStyle
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: lefthook run format --all-files
      - uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
        with:
          tool_name: code-style
          level: error
          filter_mode: nofilter
          reviewdog_flags: "-fail-level=any"
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  ensure-generated-code-is-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      # We can't use 'paths:' filters because this a required check so it
      # has to run for a pull request to be merged. Instead, we skip using a
      # conditional, this way it still counts as a run.
      - name: Get all codegen-related files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
        with:
          # SYNC: GENERATOR_PATTERNS
          files_yaml: |
            codegen:
              - "**/go.mod"
              - "go.mod"
              - "**neovim/lua/*.lua"
              - "README.md"
              - "scripts/**"
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        uses: ./.github/actions/setup
        with:
          dev-shell: ciCodegen
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        run: lefthook run --all-files generate || true
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
        with:
          tool_name: code-generation
          level: error
          filter_mode: nofilter
          reviewdog_flags: "-fail-level=any"
