name: "Check Pull Request"
on:
  workflow_dispatch:
concurrency:
  # If a run of this workflow starts and there is already an ongoing run for the same
  # branch, cancel the one in progress. I assume this will only happen if the second
  # run is for a more recent commit on the branch. In which case, I only want to run
  # checks on the most recent commit.
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash-script {0}
jobs:
  check-pull-request:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
        with:
          direnv-dev-shell: ci-check-pull-request
      # TODO: According to the lefthook documentation, this variable should _extend_
      # the output values specified in the config file, but it seems to be
      # overwriting them instead. For now, I'm duplicating the values specified in my
      # config here. I should open an issue.
      - run: LEFTHOOK_OUTPUT='execution_info,failure' lefthook run check --all-files --no-tty --colors on
