name: "Check Style"
on:
  # It should also run on pushes to the default branch to catch my mistakes, but
  # I feel like that's a waste of resources.
  pull_request:
concurrency:
  # Since we're only interested in checking the latest commit to the branch,
  # we'll limit the workflow to running at most once per branch, cancelling
  # older runs when newer ones start.
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  check-style:
    if: ${{ ! startsWith(github.head_ref, 'renovate/')  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciCheckStyle
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: treefmt --on-unmatched=fatal
      - uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
        with:
          tool_name: code-style
          level: error
          filter_mode: nofilter
          reviewdog_flags: '-fail-level=any'
