name: "Check Pull Request"
on:
  pull_request:
  push:
    # These branches get merged without a pull request being made.
    branches:
      # SYNC: AUTOMERGE_PREFIX
      - "renovate/branch-automerge/**"
# Since we're only interested in checking the latest commit to the branch, we'll
# limit the workflow to running at most once per branch, cancelling older runs when
# newer ones start.
concurrency:
  # For more information on how the branch name, is calculated see:
  # https://stackoverflow.com/a/71158878
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  lint:
    # Only run if both of the following are true:
    #   - This is not a pull request event for a Renovate automerge branch.
    #     Those are covered by the push event.
    #   - This is not a Renovate branch. I don't think a Renovate change will
    #     cause a lint issue.
    #
    # For more information on how the branch name, is calculated see:
    # https://stackoverflow.com/a/71158878
    if: ${{ (! (github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/branch-automerge/'))) && (! startsWith(github.head_ref || github.ref_name, 'renovate/')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciLint
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: |
          if ! lefthook run --all-files fix-lint; then
            echo 'DID_FAIL=true' >> "$GITHUB_ENV"
          fi
      - uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
        with:
          tool_name: lint-autofix
          level: error
          filter_mode: nofilter
          reviewdog_flags: "-fail-level=any"
      - env:
          # 'lint check' calls reviewdog so it needs a token
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! lefthook run --all-files check-lint; then
            echo 'DID_FAIL=true' >> "$GITHUB_ENV"
          fi
      # By waiting until everything has run to fail the job, we'll see all the
      # errors at once instead of fixing some errors, rerunning the job, and
      # finding more.
      - if: ${{ env.DID_FAIL == 'true' }}
        run: exit 1
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  check-style:
    # Only run if both of the following are true:
    #   - This is not a pull request event for a Renovate automerge branch.
    #     Those are covered by the push event.
    #   - This is not a Renovate branch. I don't think they'll break the
    #     code style.
    #
    # For more information on how the branch name, is calculated see:
    # https://stackoverflow.com/a/71158878
    if: ${{ (! (github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/branch-automerge/'))) && (! startsWith(github.head_ref || github.ref_name, 'renovate/')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciCheckStyle
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: lefthook run format --all-files
      - uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
        with:
          tool_name: code-style
          level: error
          filter_mode: nofilter
          reviewdog_flags: "-fail-level=any"
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  ensure-generated-code-is-up-to-date:
    # Only run if this is not a pull request event for a Renovate automerge branch.
    # Those are covered by the push event.
    if: ${{ ! (github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/branch-automerge/')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      # Ideally, I'd put this job in a separate workflow and use 'paths:' to match
      # relevant files, but since this check is required, it can't be skipped at the
      # workflow level[1] (A skip using jobs.<job_id>.if is ok though). However,
      # individual steps can be skipped. To avoid having to put a conditional over
      # every step I moved all the steps into a separate action.
      #
      # [1]:
      # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
      - name: Get all codegen-related files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
        with:
          # SYNC: GENERATOR_PATTERNS
          files_yaml: |
            codegen:
              - "**/go.mod"
              - "**neovim/lua/*.lua"
              - "README.md"
              - "scripts/**"
              - ".envrc"
              - "flake.lock"
              - "flake-modules/**"
              - "flake.nix"
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        uses: ./.github/actions/ensure-generated-code-is-up-to-date
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
