name: Check for Broken Links
on:
  workflow_dispatch:
  schedule:
    # Once a week
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  check-for-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          dev-shell: ciCheckForBrokenLinks
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@f81112d0d2814ded911bd23e3beaa9dda9093915 # v2
        with:
          args: "--verbose --no-progress ."
          # To avoid being rate-limited by GitHub
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.lychee.outputs.exit_code != 0
        run: |
          gh issue create \
            --title 'Link Checker Report' \
            --body-file ./lychee/out.md
