name: "Check Pull Request"
on:
  workflow_dispatch:
  pull_request:
  push:
    # These branches get merged without a pull request being made so we need to check
    # them too.
    branches:
      # SYNC: AUTOMERGE_PREFIX
      - "renovate/branch-automerge/**"
jobs:
  codegen-changed-files:
    # Only run this job if it wasn't triggered by a pull request event for a Renovate
    # automerge branch. Those are covered by the push event.
    if: ${{ ! (github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/branch-automerge/')) }}
    runs-on: ubuntu-latest
    outputs:
      any-changed: "true"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # For push events, we need to get the last two commits so we can get the
          # changed files between them.
          fetch-depth: ${{ github.event.name == 'push' && 2 || 1 }}
      - name: Get changed files that would trigger code generation
        id: changed-files
        uses: tj-actions/changed-files@c3a1bb2c992d77180ae65be6ae6c166cf40f857c # v45
        with:
          # SYNC: GENERATOR_PATTERNS
          files: |
            **/go.mod
            **neovim/lua/*.lua
            "README.md"
            scripts/**
            .envrc
            flake.lock
            flake-modules/**
            flake.nix
  # Ideally, I'd put this job in a separate workflow and use 'paths:' to match
  # relevant files, but since this job is a required check, it can't be skipped at
  # the workflow level[1]. A skip using jobs.<job_id>.if is allowed, but you can't
  # use the 'paths:' filter there. Since I can't use a 'paths:' filter, I decided to
  # use a separate job with an output that tells me if any relevant files were
  # changed. This way, I could use that output in my jobs.<job_id>.if condition.
  #
  # [1]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  #
  # WARNING: This name is used to specify what checks are required to merge a branch,
  # don't change it without updating the required checks as well.
  ensure-generated-code-is-up-to-date:
    concurrency:
      group: test
      cancel-in-progress: true
    needs: codegen-changed-files
    # By default, if the dependency of a required check fails or is cancelled, the
    # required check is skipped and counted as a successful check[1]. So in addition
    # to checking if a relevant file was changed, I also need to check to see if a
    # dependency failed or was cancelled. If it was, I'll fail this job as well.
    #
    # [1]: https://github.com/actions/runner/issues/2566
    if: ${{ (contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) || needs.codegen-changed-files.outputs.any-changed == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: ci-bash {0}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciCodegen
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        env:
          REASON: ${{ contains(needs.*.result, 'cancelled') && 'was cancelled' || '' }}${{ contains(needs.*.result, 'failure') && 'failed' || '' }}
        run: |
          echo "Error: Dependency job $REASON"
          exit 1
      - env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lefthook run generate --all-files
          git diff |
          ./scripts/reviewdog.bash \
            -name=code-generation \
            -f=diff \
            -f.diff.strip=1
