name: "Ensure Generated Code is Up to Date"
on:
  # It should also run on the default branch to catch my mistakes, but I feel
  # like that's a waste of resources. I'll just trust my pre-commit hook runs.
  pull_request:
concurrency:
  # Since we're only interested in checking the latest commit to the branch,
  # we'll limit the workflow to running at most once per branch, cancelling
  # older runs when newer ones start.
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  ensure-generated-code-is-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      # We can't use 'paths:' filters because this a required check so it
      # has to run for a pull request to be merged. Instead, we skip using a
      # conditional, this way it still counts as a run.
      - name: Get all codegen-related files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
        with:
          # SYNC: GENERATORS
          files_yaml: |
            codegen:
              - "**/go.mod"
              - "go.mod"
              - "**neovim/lua/*.lua"
              - "README.md"
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        uses: ./.github/actions/setup
        with:
          dev-shell: ciCodegen
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        run: bash scripts/qa/qa.bash generate || true
      - if: steps.changed-files-yaml.outputs.codegen_any_changed == 'true'
        uses: reviewdog/action-suggester@db4abb16fbaabe386831e5addb7be1485d0d63d3 # v1
        with:
          tool_name: code-generation
          level: error
          filter_mode: nofilter
          reviewdog_flags: '-fail-level=any'
