name: "Renovate Post Upgrade Task: Update nix-direnv hash in .envrc"
on:
  push:
    branches:
      # SYNC: RENOVATE_FIXUP_ENVRC RENOVATE_FIXUP
      - "renovate/fixup/envrc/**"
jobs:
  fix-envrc:
    uses: ./.github/workflows/renovate-post-upgrade-task.yml
    with:
      command: just ci fixup-renovate-pull-request-for-envrc
    secrets:
      BIGOLU_BOT_PRIVATE_KEY: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
