name: "Renovate Post Upgrade Task: Update gomod2nix.toml"
on:
  push:
    branches:
      # SYNC: RENOVATE_FIXUP_GOLANG RENOVATE_FIXUP
      - "renovate/fixup/golang/**"
jobs:
  fix-envrc:
    uses: ./.github/workflows/renovate-post-upgrade-task.yml
    with:
      command: |
        # shellcheck disable=2016
        nix shell --impure nixpkgs#fish nixpkgs#direnv \
          --command fish --command '
            direnv hook fish | source
            direnv allow
            direnv exec "$PWD" nix-direnv-reload
            direnv exec "$PWD" just generate-gomod2nix-lock
          '
    secrets:
      BIGOLU_BOT_PRIVATE_KEY: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
