name: "Renovate Post Upgrade Task: Update gomod2nix.toml"
on:
  push:
    branches:
      # SYNC: RENOVATE_FIXUP_GOLANG RENOVATE_FIXUP
      - "renovate/fixup/golang/**"
jobs:
  fix-envrc:
    uses: ./.github/workflows/renovate-post-upgrade-task.yml
    with:
      command: just generate-gomod2nix-lock
    secrets:
      BIGOLU_BOT_PRIVATE_KEY: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
