name: "Lint"
on:
  # It should also run on pushes to the default branch to catch my mistakes, but
  # I feel like that's a waste of resources. I'll just trust my pre-commit hook
  # runs.
  pull_request:
concurrency:
  # Since we're only interested in checking the latest commit to the branch,
  # we'll limit the workflow to running at most once per branch, cancelling
  # older runs when newer ones start.
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  lint:
    if: ${{ ! startsWith(github.head_ref, 'renovate/')  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/setup
        with:
          direnv-environment: ciLint
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - env:
          REPORTER: ${{ github.event_name == 'pull_request' && 'pr' || 'commit' }}
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./scripts/ci/lint.bash "$REPORTER"
