name: Lychee
on:
  workflow_dispatch:
  schedule:
    # Run once a month.
    #
    # I've chosen a non-zero minute for the workflow to run to avoid running it at
    # the start of the hour. This is because GitHub sees high load at the start of
    # every hour and when that happens, some queued jobs may be delayed or
    # dropped[1].
    #
    # [1]: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
    - cron: "43 0 1 * *"
defaults:
  run:
    shell: bash-script {0}
jobs:
  lychee:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/setup
      - name: Run lychee
        env:
          # To avoid being rate-limited by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: mise run ci:lychee
      - if: always()
        uses: ./.github/actions/save-cache
