name: Make a Release
on:
  workflow_dispatch:
  schedule:
    # Once every 3 months
    # SYNC: NEW_COMMITS_SINCE
    - cron: "0 0 1 */3 *"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  get-new-commit-count:
    name: Get New Commit Count
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.get-new-commit-count.outputs.count }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ci-get-commit-count
      # SYNC: NEW_COMMITS_SINCE
      - name: Get the number of new commits
        id: get-new-commit-count
        run: |
          echo \
            "count=$(git log --oneline --since '3 months ago' | wc -l)" \
            >> "$GITHUB_OUTPUT"
  make-assets:
    name: Make Assets
    needs: get-new-commit-count
    if: >
      github.ref_name == github.event.repository.default_branch
      && (needs.get-new-commit-count.outputs.count > 0 || github.event_name == 'workflow_dispatch')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # GitHub Actions runs macos-latest on Apple silicon so instead I'll use the
          # most recent version of macOS that they still run on Intel.
          - macos-13
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - id: make-assets
        run: ./scripts/ci/make-assets.bash
      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: artifacts-${{ matrix.os }}
          path: ${{ steps.make-assets.outputs.artifact-directory }}
  make-release:
    needs: make-assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          path: artifacts
          pattern: artifacts-*
          merge-multiple: true
      - run: ./scripts/ci/make-release.bash
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
