name: Make a Release
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash-script {0}
jobs:
  make-assets:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - name: Make Assets
        id: make-assets
        run: mise run ci:make-assets
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: assets-linux
          path: ${{ steps.make-assets.outputs.asset-directory }}
      - if: always()
        uses: ./.github/actions/save-cache
