name: Make a Release
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash-script {0}
jobs:
  make-assets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04 # renovate: github-runner
          # GitHub Actions runs macos-latest on Apple silicon so instead I'll use the
          # most recent version of macOS that they still run on Intel.
          - macos-13 # renovate: github-runner
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - id: make-assets
        run: ./.github/scripts/make-assets.bash
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: assets-${{ matrix.os }}
          path: ${{ steps.make-assets.outputs.asset-directory }}
  make-release:
    needs: make-assets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          pattern: assets-*
          merge-multiple: true
          # The destination
          path: assets
      - run: ./.github/scripts/make-release.bash
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
