name: Make a Release
on:
  workflow_dispatch:
  schedule:
    # Once every 3 months
    # SYNC: NEW_COMMITS_SINCE
    - cron: "0 0 1 */3 *"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  has-new-commits:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-24.04
    outputs:
      result: ${{ steps.has-new-commits.outputs.result }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # We need the full history to check for new commits
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - id: has-new-commits
        run: ./.github/scripts/has-new-commits.bash
  make-assets:
    needs: has-new-commits
    if: github.event_name == 'workflow_dispatch' || needs.has-new-commits.outputs.result == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04 # renovate: github-runner
          # GitHub Actions runs macos-latest on Apple silicon so instead I'll use the
          # most recent version of macOS that they still run on Intel.
          - macos-13 # renovate: github-runner
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - id: make-assets
        run: ./.github/scripts/make-assets.bash
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: assets-${{ matrix.os }}
          path: ${{ steps.make-assets.outputs.asset-directory }}
  make-release:
    needs: make-assets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          pattern: assets-*
          merge-multiple: true
          # The destination
          path: assets
      - run: ./.github/scripts/make-release.bash
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
