name: Make a Release
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash-script {0}
jobs:
  make-assets:
    strategy:
      matrix:
        os:
          - ubuntu-24.04 # renovate: github-runner
          # GitHub Actions runs macos-latest on aarch64 so instead I'll use the most
          # recent version of macOS that they still run on x64.
          - macos-13 # renovate: github-runner
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - name: Make Assets
        id: make-assets
        run: mise run ci:make-assets
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: assets-${{ matrix.os }}
          path: ${{ steps.make-assets.outputs.asset-directory }}
  make-release:
    needs: make-assets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: assets-*
          merge-multiple: true
          # The destination
          path: assets
      - name: Make the Release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: mise run ci:make-release
