name: Release
on:
  workflow_dispatch:
defaults:
  run:
    shell: nix run --file . devShells.ci-essentials -- bash-script {0}
jobs:
  make-assets:
    strategy:
      matrix:
        os:
          - ubuntu-24.04 # renovate: github-runner
          # GitHub Actions runs macos-latest on aarch64 so instead I'll use the most
          # recent version of macOS that they still run on x64.
          - macos-13 # renovate: github-runner
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/setup
      - name: Make Assets
        id: make-assets
        run: mise run ci:make-assets
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: assets-${{ matrix.os }}
          path: ${{ steps.make-assets.outputs.asset-directory }}
      - if: always()
        uses: ./.github/actions/save-cache
  release:
    needs: make-assets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          pattern: assets-*
          merge-multiple: true
          # The destination
          path: assets
      - name: Release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: mise run ci:release
      - if: always()
        uses: ./.github/actions/save-cache
