name: Release
on:
  workflow_dispatch:
defaults:
  run:
    shell: nix run --file . outputsForCurrentSystem.devShells.ci -- bash {0}
permissions:
  # `cache-nix-gc-roots-action` needs this permission to purge old caches
  actions: write
jobs:
  make-assets:
    strategy:
      matrix:
        os:
          - ubuntu-24.04 # renovate: github-runner
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/setup
      - name: Make Assets
        id: make-assets
        run: mise run ci:make-assets
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: assets-${{ matrix.os }}
          path: ${{ steps.make-assets.outputs.asset-directory }}
      - if: always()
        uses: bigolu/cache-nix-gc-roots-action/save@105282c8850c86c5303e3ec8dd2f1859e561cc0c # main
  release:
    permissions:
      # We need to this to create/delete releases
      contents: write
    needs: make-assets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: assets-*
          merge-multiple: true
          # The destination
          path: assets
      - name: Make release
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: mise run ci:release
      - if: always()
        uses: bigolu/cache-nix-gc-roots-action/save@105282c8850c86c5303e3ec8dd2f1859e561cc0c # main
