# TODO: Ideally this would a composite action. This way, the action could
# register post run steps and users would not have to force all of their upgrade
# task logic into `inputs.command`. They're considering adding it:
# https://github.com/actions/runner/issues/1478
#
# If this were an action, then this would run first and the tasks would depend on it.
# This way if a task was already run on the branch, this action could output
# something like 'already-ran' so the tasks could skip based on it. In the post-run,
# any changes would get committed.

name: "Renovate Post-Upgrade Task Runner"
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
    secrets:
      BIGOLU_BOT_PRIVATE_KEY:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true
env:
  GIT_USER: "github-actions[bot]"
  GIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  get-commit-message:
    name: Get Commit Message
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.commit-message.outputs.head-commit-message }}
      # Since you can't access the env context from job.<job_id>.if[1], I'm exposing
      # the env variable I need to access as an output on this job.
      #
      # [1]: https://github.com/github/docs/issues/21927
      git-user: ${{ env.GIT_USER }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      - uses: ./.github/actions/setup
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - id: commit-message
        run: |
          # randomly generated value using `openssl rand -base64 18`
          delimiter='UPVkbkkuL/htny+vQ2qxsNvc'
          printf \
            "head-commit-message<<%s\n%s\n%s\n" \
            "$delimiter" \
            "$(git show --no-patch --format=%B)" \
            "$delimiter" \
            >>"$GITHUB_OUTPUT"
  renovate-post-upgrade-task-runner:
    needs: get-commit-message
    if: "! contains(needs.get-commit-message.outputs.head-commit-message, needs.get-commit-message.outputs.git-user)"
    runs-on: ubuntu-latest
    steps:
      - id: bot-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # So when we commit, it triggers other workflows:
          # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ steps.bot-token.outputs.token }}
          # For more information on how the branch name, is calculated see:
          # https://stackoverflow.com/a/71158878
          ref: ${{ github.head_ref || github.ref_name }}
          # Since I'm amending a commit I need the last 2 commits instead of just 1.
          # Fetching 1 commit would overwrite the whole history.
          fetch-depth: 2
      - uses: ./.github/actions/setup
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          dev-shell: ciRenovateTaskRunner
      - run: |
          ${{ inputs.command }}
          if [ -n "$(git status --porcelain)" ]; then
            old_message="$(git show --no-patch --format=%B)"
            new_message="$old_message"$'\n'$'\n'"Co-authored-by: $GIT_USER <$GIT_EMAIL>"
            git add --all
            git \
              -c user.name="$GIT_USER" \
              -c user.email="$GIT_EMAIL" \
              commit \
              --amend \
              --message "$new_message"
            git push --force
          fi
