name: "Renovate Post-Upgrade Tasks"
on:
  push:
    branches:
      - "renovate/branch-automerge/fixup/**"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  get-script-path:
    name: Get Script Path
    runs-on: ubuntu-latest
    outputs:
      path: ${{ steps.get-script-path.outputs.path }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - id: get-script-path
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          path=
          case "$BRANCH_NAME" in
            renovate/branch-automerge/fixup/golang/*)
              path='./scripts/code-generation/generate-gomod2nix-lock.bash'
              ;;
            renovate/branch-automerge/fixup/envrc/*)
              path='./scripts/ci/set-nix-direnv-hash.bash'
              ;;
            renovate/branch-automerge/fixup/nix-version/*)
              path='./scripts/sync-nix-version.bash'
              ;;
            *)
              echo "Unknown fixup branch: $BRANCH_NAME" >&2
              exit 1
              ;;
          esac
          echo "path=$path" >> "$GITHUB_OUTPUT"
  run-post-upgrade-task:
    needs: get-script-path
    uses: ./.github/workflows/renovate-post-upgrade-task-runner.yml
    with:
      command: ${{ needs.get-script-path.outputs.path }}
    secrets:
      BIGOLU_BOT_PRIVATE_KEY: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
