name: Renovate
on:
  workflow_dispatch:
  schedule:
    # Once a day
    - cron: "0 0 * * *"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ci-renovate
      - id: bot-token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - env:
          # secrets.GITHUB_TOKEN can't be used since actions performed with that
          # token will not trigger other workflows[1].
          #
          # [1]: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          RENOVATE_TOKEN: "${{ steps.bot-token.outputs.token }}"
        run: renovate
