# TODO: Ideally this would a composite action. This way, the action could
# register post run steps and users would not have to force all of their upgrade
# task logic into `inputs.command`. They're considering adding it:
# https://github.com/actions/runner/issues/1478

name: "Renovate Post-Upgrade Task Runner"
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
    secrets:
      BIGOLU_BOT_PRIVATE_KEY:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true
jobs:
  get-commit-message:
    name: Get Commit Message
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.commit-message.outputs.HEAD_COMMIT_MESSAGE }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      - id: commit-message
        # multi-line output values require special handling so to avoid that
        # we'll only get the first line:
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter
        run: echo "HEAD_COMMIT_MESSAGE=$(git log --oneline --format=%s --max-count 1)" >> "$GITHUB_OUTPUT"
  renovate-post-upgrade-task-runner:
    needs: get-commit-message
    # TODO: This will result in a bunch of runs that immediately exit if the
    # branch wasn't just created. Ideally the job wouldn't even start if the
    # branch wasn't just created:
    if: "! contains(needs.get-commit-message.outputs.head-commit-message, vars.MARKER)"
    runs-on: ubuntu-latest
    steps:
      - id: bot-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          # So when we commit, it triggers other workflows:
          # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ steps.bot-token.outputs.token }}
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: ./.github/actions/setup
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          dev-shell: ciRenovateTaskRunner
      - run: ${{ inputs.command }}
      - env:
          MARKER: ${{ vars.MARKER }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "$MARKER fixup"
            git push
          fi
