name: "Renovate Post-Upgrade Task"
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
    secrets:
      BIGOLU_BOT_PRIVATE_KEY:
        required: true
jobs:
  renovate-post-upgrade-task:
    runs-on: ubuntu-latest
    # TODO: This will result in a bunch of runs that immediately exit if the
    # branch wasn't just created. Ideally the job wouldn't even start if the
    # branch wasn't just created:
    #
    # SYNC: RENOVATE_FIXUP
    if: startsWith(github.event.head_commit.message, '[RENOVATE_FIXUP]')
    steps:
      - id: bot-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          # So when we commit, it triggers other workflows:
          # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ steps.bot-token.outputs.token }}
      - uses: ./.github/actions/set-up-nix
        with:
          devshell-name: ciRenovate
      - run: ${{ inputs.command }}
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@48b6133aa6c826f267ebd33aa2d29470f9d9e7d0 # v1
        id: find-pull-request
        with:
          branch: ${{ github.head_ref }}
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: ${{ steps.bot-token.outputs.token }}
          pr-number: ${{ steps.find-pull-request.outputs.number }}
          configuration-path: .github/labeler.yml
