name: "Renovate Post-Upgrade Tasks"
on:
  push:
    branches:
      - "renovate/branch-automerge/fixup/**"
env:
  # The is the user information for the GitHub Actions bot[1].
  #
  # [1]: https://github.com/orgs/community/discussions/26560#discussioncomment-3252339
  GIT_USER: "github-actions[bot]"
  GIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  get-commit-message:
    name: Get Commit Message
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.commit-message.outputs.head-commit-message }}
      # Since you can't access the env context from job.<job_id>.if[1], I'm exposing
      # the env variable I need to access as an output on this job.
      #
      # [1]: https://github.com/github/docs/issues/21927
      git-user: ${{ env.GIT_USER }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
      - id: commit-message
        run: |
          # randomly generated value using `openssl rand -base64 18`
          delimiter='UPVkbkkuL/htny+vQ2qxsNvc'
          printf \
            "head-commit-message<<%s\n%s\n%s\n" \
            "$delimiter" \
            "$(git show --no-patch --format=%B)" \
            "$delimiter" \
            >>"$GITHUB_OUTPUT"
  renovate-post-upgrade-tasks:
    needs: get-commit-message
    if: "! contains(needs.get-commit-message.outputs.head-commit-message, needs.get-commit-message.outputs.git-user)"
    runs-on: ubuntu-latest
    steps:
      - id: bot-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # So when we commit, it triggers other workflows:
          # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ steps.bot-token.outputs.token }}
          ref: ${{ github.ref_name }}
          # Since I'm amending a commit I need the last 2 commits instead of just 1.
          # Fetching 1 commit would overwrite the whole history.
          fetch-depth: 2
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciRenovateTaskRunner
      - env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          case "$BRANCH_NAME" in
            renovate/branch-automerge/fixup/golang/*)
              ./scripts/code-generation/generate-gomod2nix-lock.bash
              ;;
            renovate/branch-automerge/fixup/envrc/*)
              ./scripts/ci/set-nix-direnv-hash.bash
              ;;
            renovate/branch-automerge/fixup/nix-version/*)
              ./scripts/code-generation/sync-nix-version.bash
              ;;
            *)
              echo "Unknown fixup branch: $BRANCH_NAME" >&2
              exit 1
              ;;
          esac
      - run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            old_message="$(git show --no-patch --format=%B)"
            new_message="$old_message"$'\n\n'"Co-authored-by: $GIT_USER <$GIT_EMAIL>"
            git add --all
            git \
              -c user.name="$GIT_USER" \
              -c user.email="$GIT_EMAIL" \
              commit \
              --amend \
              --message "$new_message"
            # A safer force push[1].
            #
            # [1]: https://stackoverflow.com/questions/65837109/when-should-i-use-git-push-force-if-includes
            git push --force-with-lease --force-if-includes
          fi
