name: Renovate
on:
  workflow_dispatch:
defaults:
  run:
    shell: nix run --file . devShells.ci-essentials -- bash-script {0}
jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/setup
      - uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2
        id: bot-token
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - name: Run renovate
        shell: nix run --file . devShells.ci-renovate -- bash-script {0}
        env:
          # secrets.GITHUB_TOKEN can't be used since actions performed with that
          # token will not trigger other workflows[1].
          #
          # [1]: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          RENOVATE_TOKEN: "${{ steps.bot-token.outputs.token }}"
        run: renovate
      - if: always()
        uses: ./.github/actions/save-cache
