name: Renovate
on:
  workflow_dispatch:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
        with:
          dev-shell: ciRenovate
      - id: bot-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - env:
          # This token is what Renovate will for authentication. secrets.GITHUB_TOKEN
          # can't be used since other workflows aren't triggered by actions performed
          # with that token[1]. For example, if Renovate opened a pull request using
          # secrets.GITHUB_TOKEN, pull request checks wouldn't run. This is done to
          # avoid an infinite loop of workflow triggers, which would happen if the
          # workflow dependencies had a cycle.
          #
          # [1]: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          RENOVATE_TOKEN: "${{ steps.bot-token.outputs.token }}"
        run: renovate
