name: auto-merge
on:
  workflow_dispatch:
  schedule:
    # Once daily at midnight
    - cron: "0 0 * * *"
defaults:
  run:
    shell: ci-bash {0}
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - id: bot-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        with:
          app-id: ${{ vars.BIGOLU_BOT_APP_ID }}
          private-key: ${{ secrets.BIGOLU_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          # So when we commit, it triggers other workflows:
          # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ steps.bot-token.outputs.token }}
          # By default, the commit that triggered the workflow will be checked out.
          # Instead, I want to check out the default branch so the auto-merge script
          # can push changes to it.
          ref: ${{ github.event.repository.default_branch }}
      - uses: ./.github/actions/setup
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: ./scripts/ci/auto-merge.bash
        env:
          GH_TOKEN: "${{ steps.bot-token.outputs.token }}"
