name: "Test"
on:
  # It should also run on the default branch to catch my mistakes, but I feel
  # like that's a waste of resources. The caching workflow that runs on master
  # should be enough to catch my mistakes e.g. adding a program to a platform
  # it doesn't support or adding a program that doesn't build.
  pull_request:
concurrency:
  # Since we're only interested in checking the latest commit to the branch,
  # we'll limit the workflow to running at most once per branch, cancelling
  # older runs when newer ones start.
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
env:
  REPORTER: ${{ github.event_name == 'pull_request' && 'pr' || 'commit' }}
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest uses M1 so I'll just use the most recent version of macOS
        # that they still on run intel macs
        os: [ubuntu-latest, macos-13]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/setup
        with:
          direnv-environment: ciTest
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: bash ./scripts/test.bash
