name: "Test"
on:
  pull_request:
concurrency:
  # Since we're only interested in checking the latest commit to the branch,
  # we'll limit the workflow to running at most once per branch, cancelling
  # older runs when newer ones start.
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  # WARNING: This name is used to specify what checks are required to merge a
  # branch, don't change it without updating the required checks as well.
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest uses M1 so I'll just use the most recent version of macOS
        # that they still on run intel macs
        os: [ubuntu-latest, macos-13]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      # We can't use 'paths:' filters because this a required check so it
      # has to run for a pull request to be merged. Instead, we skip using a
      # conditional, this way it still counts as a run.
      - name: Get all package-related files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@e9772d140489982e0e3704fea5ee93d536f1e275 # v45
        with:
          # Since all this test does is build packages, only run when there are
          # changes in files that could affect the package set
          files_yaml: |
            packages:
              - "flake.nix"
              - "flake.lock"
              - "flake-modules/**"
              - "!flake-modules/bundler/gozip/**"
      - if: steps.changed-files-yaml.outputs.packages_any_changed == 'true'
        uses: ./.github/actions/setup
        with:
          dev-shell: ciTest
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - if: steps.changed-files-yaml.outputs.packages_any_changed == 'true'
        run: bash ./scripts/test.bash
